export { getHeaderWithNavigationWithoutTitleMobile } from './headerWithNavigationWithoutTitleMobile/getHeaderWithNavigationWithoutTitleMobile';
export { getHeaderWithBackArrowWithCenterTitleMobile } from './headerWithBackArrowWithCenterTitleMobile/getHeaderWithBackArrowWithCenterTitleMobile';
