import { ColorValue, WithoutThemeColorValue, WithThemeColorValue } from './translatecolors';
import { Color } from './types';

export type TColorMapper = Record<Color, ColorValue>;

const getWithThemeValue = (value: string): WithThemeColorValue => ({
    type: 'WITH_THEME',
    value,
});

const getWithoutThemeValue = (value: string): WithoutThemeColorValue => ({
    type: 'WITHOUT_THEME',
    value,
});

export const colorMapper: TColorMapper = {
    accentColorPrimary: getWithThemeValue('accent-primary'),
    accentColorPrimaryHover: getWithThemeValue('accent-primary-hover'),
    accentColorPrimaryInverted: getWithThemeValue('accent-primary-inverted'),
    accentColorPrimaryInvertedHover: getWithThemeValue('accent-primary-inverted-hover'),
    accentColorPrimaryInvertedPress: getWithThemeValue('accent-primary-inverted-press'),
    accentColorPrimaryPress: getWithThemeValue('accent-primary-press'),
    accentColorSecondary: getWithThemeValue('accent-secondary'),
    accentColorSecondaryHover: getWithThemeValue('accent-secondary-hover'),
    accentColorSecondaryInverted: getWithThemeValue('accent-secondary-inverted'),
    accentColorSecondaryInvertedHover: getWithThemeValue('accent-secondary-inverted-hover'),
    accentColorSecondaryInvertedPress: getWithThemeValue('accent-secondary-inverted-press'),
    accentColorSecondaryPress: getWithThemeValue('accent-secondary-press'),
    backgroundColorAccent: getWithThemeValue('bg-accent'),
    backgroundColorAttentionMuted: getWithThemeValue('bg-attention-muted'),
    backgroundColorComponent: getWithThemeValue('bg-component'),
    backgroundColorComponentInverted: getWithThemeValue('bg-component-inverted'),
    backgroundColorInfo: getWithThemeValue('bg-info'),
    backgroundColorInfoMuted: getWithThemeValue('bg-info-muted'),
    backgroundColorLinkMuted: getWithThemeValue('bg-link-muted'),
    backgroundColorNegativeMuted: getWithThemeValue('bg-negative-muted'),
    backgroundColorNeutral: getWithThemeValue('bg-neutral'),
    backgroundColorNulled: getWithThemeValue('bg-nulled'),
    backgroundColorOpaque: getWithThemeValue('bg-opaque'),
    backgroundColorOverlay: getWithThemeValue('bg-overlay'),
    backgroundColorPositiveMuted: getWithThemeValue('bg-positive-muted'),
    backgroundColorPrimary: getWithThemeValue('bg-primary'),
    backgroundColorPrimaryGrouped: getWithThemeValue('bg-primary-grouped'),
    backgroundColorPrimaryInverted: getWithThemeValue('bg-primary-inverted'),
    backgroundColorQuaternary: getWithThemeValue('bg-quaternary'),
    backgroundColorQuaternaryInverted: getWithThemeValue('bg-quaternary-inverted'),
    backgroundColorSecondary: getWithThemeValue('bg-secondary'),
    backgroundColorSecondaryGrouped: getWithThemeValue('bg-secondary-grouped'),
    backgroundColorSecondaryInverted: getWithThemeValue('bg-secondary-inverted'),
    backgroundColorTertiary: getWithThemeValue('bg-tertiary'),
    backgroundColorTertiaryGrouped: getWithThemeValue('bg-tertiary-grouped'),
    backgroundColorTertiaryInverted: getWithThemeValue('bg-tertiary-inverted'),
    baseBgAltColorPrimary: getWithThemeValue('base-bg-alt-primary'),
    baseBgAltColorPrimaryInverted: getWithThemeValue('base-bg-alt-primary-inverted'),
    baseBgAltColorSecondary: getWithThemeValue('base-bg-alt-secondary'),
    baseBgAltColorSecondaryInverted: getWithThemeValue('base-bg-alt-secondary-inverted'),
    baseBgAltColorTertiary: getWithThemeValue('base-bg-alt-tertiary'),
    baseBgAltColorTertiaryInverted: getWithThemeValue('base-bg-alt-tertiary-inverted'),
    baseBgColorPrimary: getWithThemeValue('base-bg-primary'),
    baseBgColorPrimaryInverted: getWithThemeValue('base-bg-primary-inverted'),
    baseBgColorSecondary: getWithThemeValue('base-bg-secondary'),
    baseBgColorSecondaryInverted: getWithThemeValue('base-bg-secondary-inverted'),
    baseBgColorTertiary: getWithThemeValue('base-bg-tertiary'),
    baseBgColorTertiaryInverted: getWithThemeValue('base-bg-tertiary-inverted'),
    borderColorAccent: getWithThemeValue('border-accent'),
    borderColorKey: getWithThemeValue('border-key'),
    borderColorKeyInverted: getWithThemeValue('border-key-inverted'),
    borderColorLink: getWithThemeValue('border-link'),
    borderColorPrimary: getWithThemeValue('border-primary'),
    borderColorPrimaryInverted: getWithThemeValue('border-primary-inverted'),
    borderColorSecondary: getWithThemeValue('border-secondary'),
    borderColorSecondaryInverted: getWithThemeValue('border-secondary-inverted'),
    borderColorTertiary: getWithThemeValue('border-tertiary'),
    borderColorTertiaryInverted: getWithThemeValue('border-tertiary-inverted'),
    borderColorUnderline: getWithThemeValue('border-underline'),
    borderColorUnderlineInverted: getWithThemeValue('border-underline-inverted'),
    decorativeColorBlue: getWithThemeValue('decorative-blue'),
    decorativeColorBlueHover: getWithThemeValue('decorative-blue-hover'),
    decorativeColorBlueInverted: getWithThemeValue('decorative-blue-inverted'),
    decorativeColorBlueInvertedHover: getWithThemeValue('decorative-blue-inverted-hover'),
    decorativeColorBlueInvertedPress: getWithThemeValue('decorative-blue-inverted-press'),
    decorativeColorBluePress: getWithThemeValue('decorative-blue-press'),
    decorativeColorCyan: getWithThemeValue('decorative-cyan'),
    decorativeColorCyanHover: getWithThemeValue('decorative-cyan-hover'),
    decorativeColorCyanInverted: getWithThemeValue('decorative-cyan-inverted'),
    decorativeColorCyanInvertedHover: getWithThemeValue('decorative-cyan-inverted-hover'),
    decorativeColorCyanInvertedPress: getWithThemeValue('decorative-cyan-inverted-press'),
    decorativeColorCyanPress: getWithThemeValue('decorative-cyan-press'),
    decorativeColorFuchsia: getWithThemeValue('decorative-fuchsia'),
    decorativeColorFuchsiaHover: getWithThemeValue('decorative-fuchsia-hover'),
    decorativeColorFuchsiaInverted: getWithThemeValue('decorative-fuchsia-inverted'),
    decorativeColorFuchsiaInvertedHover: getWithThemeValue('decorative-fuchsia-inverted-hover'),
    decorativeColorFuchsiaInvertedPress: getWithThemeValue('decorative-fuchsia-inverted-press'),
    decorativeColorFuchsiaPress: getWithThemeValue('decorative-fuchsia-press'),
    decorativeColorGreen: getWithThemeValue('decorative-green'),
    decorativeColorGreenHover: getWithThemeValue('decorative-green-hover'),
    decorativeColorGreenInverted: getWithThemeValue('decorative-green-inverted'),
    decorativeColorGreenInvertedHover: getWithThemeValue('decorative-green-inverted-hover'),
    decorativeColorGreenInvertedPress: getWithThemeValue('decorative-green-inverted-press'),
    decorativeColorGreenPress: getWithThemeValue('decorative-green-press'),
    decorativeColorIndigo: getWithThemeValue('decorative-indigo'),
    decorativeColorIndigoHover: getWithThemeValue('decorative-indigo-hover'),
    decorativeColorIndigoInverted: getWithThemeValue('decorative-indigo-inverted'),
    decorativeColorIndigoInvertedHover: getWithThemeValue('decorative-indigo-inverted-hover'),
    decorativeColorIndigoInvertedPress: getWithThemeValue('decorative-indigo-inverted-press'),
    decorativeColorIndigoPress: getWithThemeValue('decorative-indigo-press'),
    decorativeColorJungle: getWithThemeValue('decorative-jungle'),
    decorativeColorJungleHover: getWithThemeValue('decorative-jungle-hover'),
    decorativeColorJungleInverted: getWithThemeValue('decorative-jungle-inverted'),
    decorativeColorJungleInvertedHover: getWithThemeValue('decorative-jungle-inverted-hover'),
    decorativeColorJungleInvertedPress: getWithThemeValue('decorative-jungle-inverted-press'),
    decorativeColorJunglePress: getWithThemeValue('decorative-jungle-press'),
    decorativeColorMagenta: getWithThemeValue('decorative-magenta'),
    decorativeColorMagentaHover: getWithThemeValue('decorative-magenta-hover'),
    decorativeColorMagentaInverted: getWithThemeValue('decorative-magenta-inverted'),
    decorativeColorMagentaInvertedHover: getWithThemeValue('decorative-magenta-inverted-hover'),
    decorativeColorMagentaInvertedPress: getWithThemeValue('decorative-magenta-inverted-press'),
    decorativeColorMagentaPress: getWithThemeValue('decorative-magenta-press'),
    decorativeColorOrange: getWithThemeValue('decorative-orange'),
    decorativeColorOrangeHover: getWithThemeValue('decorative-orange-hover'),
    decorativeColorOrangeInverted: getWithThemeValue('decorative-orange-inverted'),
    decorativeColorOrangeInvertedHover: getWithThemeValue('decorative-orange-inverted-hover'),
    decorativeColorOrangeInvertedPress: getWithThemeValue('decorative-orange-inverted-press'),
    decorativeColorOrangePress: getWithThemeValue('decorative-orange-press'),
    decorativeColorPistachio: getWithThemeValue('decorative-pistachio'),
    decorativeColorPistachioHover: getWithThemeValue('decorative-pistachio-hover'),
    decorativeColorPistachioInverted: getWithThemeValue('decorative-pistachio-inverted'),
    decorativeColorPistachioInvertedHover: getWithThemeValue('decorative-pistachio-inverted-hover'),
    decorativeColorPistachioInvertedPress: getWithThemeValue('decorative-pistachio-inverted-press'),
    decorativeColorPistachioPress: getWithThemeValue('decorative-pistachio-press'),
    decorativeColorPurple: getWithThemeValue('decorative-purple'),
    decorativeColorPurpleHover: getWithThemeValue('decorative-purple-hover'),
    decorativeColorPurpleInverted: getWithThemeValue('decorative-purple-inverted'),
    decorativeColorPurpleInvertedHover: getWithThemeValue('decorative-purple-inverted-hover'),
    decorativeColorPurpleInvertedPress: getWithThemeValue('decorative-purple-inverted-press'),
    decorativeColorPurplePress: getWithThemeValue('decorative-purple-press'),
    decorativeColorRed: getWithThemeValue('decorative-red'),
    decorativeColorRedInverted: getWithThemeValue('decorative-red-inverted'),
    decorativeColorTeal: getWithThemeValue('decorative-teal'),
    decorativeColorTealHover: getWithThemeValue('decorative-teal-hover'),
    decorativeColorTealInverted: getWithThemeValue('decorative-teal-inverted'),
    decorativeColorTealInvertedHover: getWithThemeValue('decorative-teal-inverted-hover'),
    decorativeColorTealInvertedPress: getWithThemeValue('decorative-teal-inverted-press'),
    decorativeColorTealPress: getWithThemeValue('decorative-teal-press'),
    decorativeColorYellow: getWithThemeValue('decorative-yellow'),
    decorativeColorYellowInverted: getWithThemeValue('decorative-yellow-inverted'),
    decorativeMutedAltColorBlue: getWithThemeValue('decorative-muted-alt-blue'),
    decorativeMutedAltColorBlueHover: getWithThemeValue('decorative-muted-alt-blue-hover'),
    decorativeMutedAltColorBlueInverted: getWithThemeValue('decorative-muted-alt-blue-inverted'),
    decorativeMutedAltColorBlueInvertedHover: getWithThemeValue(
        'decorative-muted-alt-blue-inverted-hover',
    ),
    decorativeMutedAltColorBlueInvertedPress: getWithThemeValue(
        'decorative-muted-alt-blue-inverted-press',
    ),
    decorativeMutedAltColorBluePress: getWithThemeValue('decorative-muted-alt-blue-press'),
    decorativeMutedAltColorCyan: getWithThemeValue('decorative-muted-alt-cyan'),
    decorativeMutedAltColorCyanHover: getWithThemeValue('decorative-muted-alt-cyan-hover'),
    decorativeMutedAltColorCyanInverted: getWithThemeValue('decorative-muted-alt-cyan-inverted'),
    decorativeMutedAltColorCyanInvertedHover: getWithThemeValue(
        'decorative-muted-alt-cyan-inverted-hover',
    ),
    decorativeMutedAltColorCyanInvertedPress: getWithThemeValue(
        'decorative-muted-alt-cyan-inverted-press',
    ),
    decorativeMutedAltColorCyanPress: getWithThemeValue('decorative-muted-alt-cyan-press'),
    decorativeMutedAltColorFuchsia: getWithThemeValue('decorative-muted-alt-fuchsia'),
    decorativeMutedAltColorFuchsiaHover: getWithThemeValue('decorative-muted-alt-fuchsia-hover'),
    decorativeMutedAltColorFuchsiaInverted: getWithThemeValue(
        'decorative-muted-alt-fuchsia-inverted',
    ),
    decorativeMutedAltColorFuchsiaInvertedHover: getWithThemeValue(
        'decorative-muted-alt-fuchsia-inverted-hover',
    ),
    decorativeMutedAltColorFuchsiaInvertedPress: getWithThemeValue(
        'decorative-muted-alt-fuchsia-inverted-press',
    ),
    decorativeMutedAltColorFuchsiaPress: getWithThemeValue('decorative-muted-alt-fuchsia-press'),
    decorativeMutedAltColorGreen: getWithThemeValue('decorative-muted-alt-green'),
    decorativeMutedAltColorGreenHover: getWithThemeValue('decorative-muted-alt-green-hover'),
    decorativeMutedAltColorGreenInverted: getWithThemeValue('decorative-muted-alt-green-inverted'),
    decorativeMutedAltColorGreenInvertedHover: getWithThemeValue(
        'decorative-muted-alt-green-inverted-hover',
    ),
    decorativeMutedAltColorGreenInvertedPress: getWithThemeValue(
        'decorative-muted-alt-green-inverted-press',
    ),
    decorativeMutedAltColorGreenPress: getWithThemeValue('decorative-muted-alt-green-press'),
    decorativeMutedAltColorIndigo: getWithThemeValue('decorative-muted-alt-indigo'),
    decorativeMutedAltColorIndigoHover: getWithThemeValue('decorative-muted-alt-indigo-hover'),
    decorativeMutedAltColorIndigoInverted: getWithThemeValue(
        'decorative-muted-alt-indigo-inverted',
    ),
    decorativeMutedAltColorIndigoInvertedHover: getWithThemeValue(
        'decorative-muted-alt-indigo-inverted-hover',
    ),
    decorativeMutedAltColorIndigoInvertedPress: getWithThemeValue(
        'decorative-muted-alt-indigo-inverted-press',
    ),
    decorativeMutedAltColorIndigoPress: getWithThemeValue('decorative-muted-alt-indigo-press'),
    decorativeMutedAltColorJungle: getWithThemeValue('decorative-muted-alt-jungle'),
    decorativeMutedAltColorJungleHover: getWithThemeValue('decorative-muted-alt-jungle-hover'),
    decorativeMutedAltColorJungleInverted: getWithThemeValue(
        'decorative-muted-alt-jungle-inverted',
    ),
    decorativeMutedAltColorJungleInvertedHover: getWithThemeValue(
        'decorative-muted-alt-jungle-inverted-hover',
    ),
    decorativeMutedAltColorJungleInvertedPress: getWithThemeValue(
        'decorative-muted-alt-jungle-inverted-press',
    ),
    decorativeMutedAltColorJunglePress: getWithThemeValue('decorative-muted-alt-jungle-press'),
    decorativeMutedAltColorMagenta: getWithThemeValue('decorative-muted-alt-magenta'),
    decorativeMutedAltColorMagentaHover: getWithThemeValue('decorative-muted-alt-magenta-hover'),
    decorativeMutedAltColorMagentaInverted: getWithThemeValue(
        'decorative-muted-alt-magenta-inverted',
    ),
    decorativeMutedAltColorMagentaInvertedHover: getWithThemeValue(
        'decorative-muted-alt-magenta-inverted-hover',
    ),
    decorativeMutedAltColorMagentaInvertedPress: getWithThemeValue(
        'decorative-muted-alt-magenta-inverted-press',
    ),
    decorativeMutedAltColorMagentaPress: getWithThemeValue('decorative-muted-alt-magenta-press'),
    decorativeMutedAltColorOrange: getWithThemeValue('decorative-muted-alt-orange'),
    decorativeMutedAltColorOrangeHover: getWithThemeValue('decorative-muted-alt-orange-hover'),
    decorativeMutedAltColorOrangeInverted: getWithThemeValue(
        'decorative-muted-alt-orange-inverted',
    ),
    decorativeMutedAltColorOrangeInvertedHover: getWithThemeValue(
        'decorative-muted-alt-orange-inverted-hover',
    ),
    decorativeMutedAltColorOrangeInvertedPress: getWithThemeValue(
        'decorative-muted-alt-orange-inverted-press',
    ),
    decorativeMutedAltColorOrangePress: getWithThemeValue('decorative-muted-alt-orange-press'),
    decorativeMutedAltColorPistachio: getWithThemeValue('decorative-muted-alt-pistachio'),
    decorativeMutedAltColorPistachioHover: getWithThemeValue(
        'decorative-muted-alt-pistachio-hover',
    ),
    decorativeMutedAltColorPistachioInverted: getWithThemeValue(
        'decorative-muted-alt-pistachio-inverted',
    ),
    decorativeMutedAltColorPistachioInvertedHover: getWithThemeValue(
        'decorative-muted-alt-pistachio-inverted-hover',
    ),
    decorativeMutedAltColorPistachioInvertedPress: getWithThemeValue(
        'decorative-muted-alt-pistachio-inverted-press',
    ),
    decorativeMutedAltColorPistachioPress: getWithThemeValue(
        'decorative-muted-alt-pistachio-press',
    ),
    decorativeMutedAltColorPurple: getWithThemeValue('decorative-muted-alt-purple'),
    decorativeMutedAltColorPurpleHover: getWithThemeValue('decorative-muted-alt-purple-hover'),
    decorativeMutedAltColorPurpleInverted: getWithThemeValue(
        'decorative-muted-alt-purple-inverted',
    ),
    decorativeMutedAltColorPurpleInvertedHover: getWithThemeValue(
        'decorative-muted-alt-purple-inverted-hover',
    ),
    decorativeMutedAltColorPurpleInvertedPress: getWithThemeValue(
        'decorative-muted-alt-purple-inverted-press',
    ),
    decorativeMutedAltColorPurplePress: getWithThemeValue('decorative-muted-alt-purple-press'),
    decorativeMutedAltColorRed: getWithThemeValue('decorative-muted-alt-red'),
    decorativeMutedAltColorRedInverted: getWithThemeValue('decorative-muted-alt-red-inverted'),
    decorativeMutedAltColorTeal: getWithThemeValue('decorative-muted-alt-teal'),
    decorativeMutedAltColorTealHover: getWithThemeValue('decorative-muted-alt-teal-hover'),
    decorativeMutedAltColorTealInverted: getWithThemeValue('decorative-muted-alt-teal-inverted'),
    decorativeMutedAltColorTealInvertedHover: getWithThemeValue(
        'decorative-muted-alt-teal-inverted-hover',
    ),
    decorativeMutedAltColorTealInvertedPress: getWithThemeValue(
        'decorative-muted-alt-teal-inverted-press',
    ),
    decorativeMutedAltColorTealPress: getWithThemeValue('decorative-muted-alt-teal-press'),
    decorativeMutedAltColorYellow: getWithThemeValue('decorative-muted-alt-yellow'),
    decorativeMutedAltColorYellowInverted: getWithThemeValue(
        'decorative-muted-alt-yellow-inverted',
    ),
    decorativeMutedColorBlue: getWithThemeValue('decorative-muted-blue'),
    decorativeMutedColorBlueHover: getWithThemeValue('decorative-muted-blue-hover'),
    decorativeMutedColorBlueInverted: getWithThemeValue('decorative-muted-blue-inverted'),
    decorativeMutedColorBlueInvertedHover: getWithThemeValue(
        'decorative-muted-blue-inverted-hover',
    ),
    decorativeMutedColorBlueInvertedPress: getWithThemeValue(
        'decorative-muted-blue-inverted-press',
    ),
    decorativeMutedColorBluePress: getWithThemeValue('decorative-muted-blue-press'),
    decorativeMutedColorCyan: getWithThemeValue('decorative-muted-cyan'),
    decorativeMutedColorCyanHover: getWithThemeValue('decorative-muted-cyan-hover'),
    decorativeMutedColorCyanInverted: getWithThemeValue('decorative-muted-cyan-inverted'),
    decorativeMutedColorCyanInvertedHover: getWithThemeValue(
        'decorative-muted-cyan-inverted-hover',
    ),
    decorativeMutedColorCyanInvertedPress: getWithThemeValue(
        'decorative-muted-cyan-inverted-press',
    ),
    decorativeMutedColorCyanPress: getWithThemeValue('decorative-muted-cyan-press'),
    decorativeMutedColorFuchsia: getWithThemeValue('decorative-muted-fuchsia'),
    decorativeMutedColorFuchsiaHover: getWithThemeValue('decorative-muted-fuchsia-hover'),
    decorativeMutedColorFuchsiaInverted: getWithThemeValue('decorative-muted-fuchsia-inverted'),
    decorativeMutedColorFuchsiaInvertedHover: getWithThemeValue(
        'decorative-muted-fuchsia-inverted-hover',
    ),
    decorativeMutedColorFuchsiaInvertedPress: getWithThemeValue(
        'decorative-muted-fuchsia-inverted-press',
    ),
    decorativeMutedColorFuchsiaPress: getWithThemeValue('decorative-muted-fuchsia-press'),
    decorativeMutedColorGreen: getWithThemeValue('decorative-muted-green'),
    decorativeMutedColorGreenHover: getWithThemeValue('decorative-muted-green-hover'),
    decorativeMutedColorGreenInverted: getWithThemeValue('decorative-muted-green-inverted'),
    decorativeMutedColorGreenInvertedHover: getWithThemeValue(
        'decorative-muted-green-inverted-hover',
    ),
    decorativeMutedColorGreenInvertedPress: getWithThemeValue(
        'decorative-muted-green-inverted-press',
    ),
    decorativeMutedColorGreenPress: getWithThemeValue('decorative-muted-green-press'),
    decorativeMutedColorIndigo: getWithThemeValue('decorative-muted-indigo'),
    decorativeMutedColorIndigoHover: getWithThemeValue('decorative-muted-indigo-hover'),
    decorativeMutedColorIndigoInverted: getWithThemeValue('decorative-muted-indigo-inverted'),
    decorativeMutedColorIndigoInvertedHover: getWithThemeValue(
        'decorative-muted-indigo-inverted-hover',
    ),
    decorativeMutedColorIndigoInvertedPress: getWithThemeValue(
        'decorative-muted-indigo-inverted-press',
    ),
    decorativeMutedColorIndigoPress: getWithThemeValue('decorative-muted-indigo-press'),
    decorativeMutedColorJungle: getWithThemeValue('decorative-muted-jungle'),
    decorativeMutedColorJungleHover: getWithThemeValue('decorative-muted-jungle-hover'),
    decorativeMutedColorJungleInverted: getWithThemeValue('decorative-muted-jungle-inverted'),
    decorativeMutedColorJungleInvertedHover: getWithThemeValue(
        'decorative-muted-jungle-inverted-hover',
    ),
    decorativeMutedColorJungleInvertedPress: getWithThemeValue(
        'decorative-muted-jungle-inverted-press',
    ),
    decorativeMutedColorJunglePress: getWithThemeValue('decorative-muted-jungle-press'),
    decorativeMutedColorMagenta: getWithThemeValue('decorative-muted-magenta'),
    decorativeMutedColorMagentaHover: getWithThemeValue('decorative-muted-magenta-hover'),
    decorativeMutedColorMagentaInverted: getWithThemeValue('decorative-muted-magenta-inverted'),
    decorativeMutedColorMagentaInvertedHover: getWithThemeValue(
        'decorative-muted-magenta-inverted-hover',
    ),
    decorativeMutedColorMagentaInvertedPress: getWithThemeValue(
        'decorative-muted-magenta-inverted-press',
    ),
    decorativeMutedColorMagentaPress: getWithThemeValue('decorative-muted-magenta-press'),
    decorativeMutedColorOrange: getWithThemeValue('decorative-muted-orange'),
    decorativeMutedColorOrangeHover: getWithThemeValue('decorative-muted-orange-hover'),
    decorativeMutedColorOrangeInverted: getWithThemeValue('decorative-muted-orange-inverted'),
    decorativeMutedColorOrangeInvertedHover: getWithThemeValue(
        'decorative-muted-orange-inverted-hover',
    ),
    decorativeMutedColorOrangeInvertedPress: getWithThemeValue(
        'decorative-muted-orange-inverted-press',
    ),
    decorativeMutedColorOrangePress: getWithThemeValue('decorative-muted-orange-press'),
    decorativeMutedColorPistachio: getWithThemeValue('decorative-muted-pistachio'),
    decorativeMutedColorPistachioHover: getWithThemeValue('decorative-muted-pistachio-hover'),
    decorativeMutedColorPistachioInverted: getWithThemeValue('decorative-muted-pistachio-inverted'),
    decorativeMutedColorPistachioInvertedHover: getWithThemeValue(
        'decorative-muted-pistachio-inverted-hover',
    ),
    decorativeMutedColorPistachioInvertedPress: getWithThemeValue(
        'decorative-muted-pistachio-inverted-press',
    ),
    decorativeMutedColorPistachioPress: getWithThemeValue('decorative-muted-pistachio-press'),
    decorativeMutedColorPurple: getWithThemeValue('decorative-muted-purple'),
    decorativeMutedColorPurpleHover: getWithThemeValue('decorative-muted-purple-hover'),
    decorativeMutedColorPurpleInverted: getWithThemeValue('decorative-muted-purple-inverted'),
    decorativeMutedColorPurpleInvertedHover: getWithThemeValue(
        'decorative-muted-purple-inverted-hover',
    ),
    decorativeMutedColorPurpleInvertedPress: getWithThemeValue(
        'decorative-muted-purple-inverted-press',
    ),
    decorativeMutedColorPurplePress: getWithThemeValue('decorative-muted-purple-press'),
    decorativeMutedColorRed: getWithThemeValue('decorative-muted-red'),
    decorativeMutedColorRedInverted: getWithThemeValue('decorative-muted-red-inverted'),
    decorativeMutedColorTeal: getWithThemeValue('decorative-muted-teal'),
    decorativeMutedColorTealHover: getWithThemeValue('decorative-muted-teal-hover'),
    decorativeMutedColorTealInverted: getWithThemeValue('decorative-muted-teal-inverted'),
    decorativeMutedColorTealInvertedHover: getWithThemeValue(
        'decorative-muted-teal-inverted-hover',
    ),
    decorativeMutedColorTealInvertedPress: getWithThemeValue(
        'decorative-muted-teal-inverted-press',
    ),
    decorativeMutedColorTealPress: getWithThemeValue('decorative-muted-teal-press'),
    decorativeMutedColorYellow: getWithThemeValue('decorative-muted-yellow'),
    decorativeMutedColorYellowInverted: getWithThemeValue('decorative-muted-yellow-inverted'),
    decorativeTextColorBlue: getWithThemeValue('decorative-text-blue'),
    decorativeTextColorBlueInverted: getWithThemeValue('decorative-text-blue-inverted'),
    decorativeTextColorCyan: getWithThemeValue('decorative-text-cyan'),
    decorativeTextColorCyanInverted: getWithThemeValue('decorative-text-cyan-inverted'),
    decorativeTextColorFuchsia: getWithThemeValue('decorative-text-fuchsia'),
    decorativeTextColorFuchsiaInverted: getWithThemeValue('decorative-text-fuchsia-inverted'),
    decorativeTextColorGreen: getWithThemeValue('decorative-text-green'),
    decorativeTextColorGreenInverted: getWithThemeValue('decorative-text-green-inverted'),
    decorativeTextColorIndigo: getWithThemeValue('decorative-text-indigo'),
    decorativeTextColorIndigoInverted: getWithThemeValue('decorative-text-indigo-inverted'),
    decorativeTextColorJungle: getWithThemeValue('decorative-text-jungle'),
    decorativeTextColorJungleInverted: getWithThemeValue('decorative-text-jungle-inverted'),
    decorativeTextColorMagenta: getWithThemeValue('decorative-text-magenta'),
    decorativeTextColorMagentaInverted: getWithThemeValue('decorative-text-magenta-inverted'),
    decorativeTextColorOrange: getWithThemeValue('decorative-text-orange'),
    decorativeTextColorOrangeInverted: getWithThemeValue('decorative-text-orange-inverted'),
    decorativeTextColorPistachio: getWithThemeValue('decorative-text-pistachio'),
    decorativeTextColorPistachioInverted: getWithThemeValue('decorative-text-pistachio-inverted'),
    decorativeTextColorPurple: getWithThemeValue('decorative-text-purple'),
    decorativeTextColorPurpleInverted: getWithThemeValue('decorative-text-purple-inverted'),
    decorativeTextColorRed: getWithThemeValue('decorative-text-red'),
    decorativeTextColorRedInverted: getWithThemeValue('decorative-text-red-inverted'),
    decorativeTextColorTeal: getWithThemeValue('decorative-text-teal'),
    decorativeTextColorTealInverted: getWithThemeValue('decorative-text-teal-inverted'),
    decorativeTextColorYellow: getWithThemeValue('decorative-text-yellow'),
    decorativeTextColorYellowInverted: getWithThemeValue('decorative-text-yellow-inverted'),
    graphicColorAccent: getWithThemeValue('graphic-accent'),
    graphicColorAttention: getWithThemeValue('graphic-attention'),
    graphicColorLink: getWithThemeValue('graphic-link'),
    graphicColorNegative: getWithThemeValue('graphic-negative'),
    graphicColorNeutral: getWithThemeValue('graphic-neutral'),
    graphicColorPositive: getWithThemeValue('graphic-positive'),
    graphicColorPrimary: getWithThemeValue('graphic-primary'),
    graphicColorPrimaryInverted: getWithThemeValue('graphic-primary-inverted'),
    graphicColorQuaternary: getWithThemeValue('graphic-quaternary'),
    graphicColorQuaternaryInverted: getWithThemeValue('graphic-quaternary-inverted'),
    graphicColorSecondary: getWithThemeValue('graphic-secondary'),
    graphicColorSecondaryInverted: getWithThemeValue('graphic-secondary-inverted'),
    graphicColorTertiary: getWithThemeValue('graphic-tertiary'),
    graphicColorTertiaryInverted: getWithThemeValue('graphic-tertiary-inverted'),
    modalBgAltColorPrimary: getWithThemeValue('modal-bg-alt-primary'),
    modalBgAltColorPrimaryInverted: getWithThemeValue('modal-bg-alt-primary-inverted'),
    modalBgAltColorSecondary: getWithThemeValue('modal-bg-alt-secondary'),
    modalBgAltColorSecondaryInverted: getWithThemeValue('modal-bg-alt-secondary-inverted'),
    modalBgAltColorTertiary: getWithThemeValue('modal-bg-alt-tertiary'),
    modalBgAltColorTertiaryInverted: getWithThemeValue('modal-bg-alt-tertiary-inverted'),
    modalBgColorPrimary: getWithThemeValue('modal-bg-primary'),
    modalBgColorPrimaryInverted: getWithThemeValue('modal-bg-primary-inverted'),
    modalBgColorSecondary: getWithThemeValue('modal-bg-secondary'),
    modalBgColorSecondaryInverted: getWithThemeValue('modal-bg-secondary-inverted'),
    modalBgColorTertiary: getWithThemeValue('modal-bg-tertiary'),
    modalBgColorTertiaryInverted: getWithThemeValue('modal-bg-tertiary-inverted'),
    neutralColor0: getWithThemeValue('neutral-0'),
    neutralColor0Hover: getWithThemeValue('neutral-0-hover'),
    neutralColor0Inverted: getWithThemeValue('neutral-0-inverted'),
    neutralColor0InvertedHover: getWithThemeValue('neutral-0-inverted-hover'),
    neutralColor0InvertedPress: getWithThemeValue('neutral-0-inverted-press'),
    neutralColor0Press: getWithThemeValue('neutral-0-press'),
    neutralColor100: getWithThemeValue('neutral-100'),
    neutralColor100Hover: getWithThemeValue('neutral-100-hover'),
    neutralColor100Inverted: getWithThemeValue('neutral-100-inverted'),
    neutralColor100InvertedHover: getWithThemeValue('neutral-100-inverted-hover'),
    neutralColor100InvertedPress: getWithThemeValue('neutral-100-inverted-press'),
    neutralColor100Press: getWithThemeValue('neutral-100-press'),
    neutralColor1500: getWithThemeValue('neutral-1500'),
    neutralColor1500Hover: getWithThemeValue('neutral-1500-hover'),
    neutralColor1500Inverted: getWithThemeValue('neutral-1500-inverted'),
    neutralColor1500InvertedHover: getWithThemeValue('neutral-1500-inverted-hover'),
    neutralColor1500InvertedPress: getWithThemeValue('neutral-1500-inverted-press'),
    neutralColor1500Press: getWithThemeValue('neutral-1500-press'),
    neutralColor200: getWithThemeValue('neutral-200'),
    neutralColor200Hover: getWithThemeValue('neutral-200-hover'),
    neutralColor200Inverted: getWithThemeValue('neutral-200-inverted'),
    neutralColor200InvertedHover: getWithThemeValue('neutral-200-inverted-hover'),
    neutralColor200InvertedPress: getWithThemeValue('neutral-200-inverted-press'),
    neutralColor200Press: getWithThemeValue('neutral-200-press'),
    neutralColor300: getWithThemeValue('neutral-300'),
    neutralColor300Hover: getWithThemeValue('neutral-300-hover'),
    neutralColor300Inverted: getWithThemeValue('neutral-300-inverted'),
    neutralColor300InvertedHover: getWithThemeValue('neutral-300-inverted-hover'),
    neutralColor300InvertedPress: getWithThemeValue('neutral-300-inverted-press'),
    neutralColor300Press: getWithThemeValue('neutral-300-press'),
    neutralColor400: getWithThemeValue('neutral-400'),
    neutralColor400Hover: getWithThemeValue('neutral-400-hover'),
    neutralColor400Inverted: getWithThemeValue('neutral-400-inverted'),
    neutralColor400InvertedHover: getWithThemeValue('neutral-400-inverted-hover'),
    neutralColor400InvertedPress: getWithThemeValue('neutral-400-inverted-press'),
    neutralColor400Press: getWithThemeValue('neutral-400-press'),
    neutralColor500: getWithThemeValue('neutral-500'),
    neutralColor500Hover: getWithThemeValue('neutral-500-hover'),
    neutralColor500Inverted: getWithThemeValue('neutral-500-inverted'),
    neutralColor500InvertedHover: getWithThemeValue('neutral-500-inverted-hover'),
    neutralColor500InvertedPress: getWithThemeValue('neutral-500-inverted-press'),
    neutralColor500Press: getWithThemeValue('neutral-500-press'),
    neutralColor700: getWithThemeValue('neutral-700'),
    neutralColor700Hover: getWithThemeValue('neutral-700-hover'),
    neutralColor700Inverted: getWithThemeValue('neutral-700-inverted'),
    neutralColor700InvertedHover: getWithThemeValue('neutral-700-inverted-hover'),
    neutralColor700InvertedPress: getWithThemeValue('neutral-700-inverted-press'),
    neutralColor700Press: getWithThemeValue('neutral-700-press'),
    neutralTranslucentColor0: getWithThemeValue('neutral-translucent-0'),
    neutralTranslucentColor0Hover: getWithThemeValue('neutral-translucent-0-hover'),
    neutralTranslucentColor0Inverted: getWithThemeValue('neutral-translucent-0-inverted'),
    neutralTranslucentColor0InvertedHover: getWithThemeValue(
        'neutral-translucent-0-inverted-hover',
    ),
    neutralTranslucentColor0InvertedPress: getWithThemeValue(
        'neutral-translucent-0-inverted-press',
    ),
    neutralTranslucentColor0Press: getWithThemeValue('neutral-translucent-0-press'),
    neutralTranslucentColor100: getWithThemeValue('neutral-translucent-100'),
    neutralTranslucentColor100Hover: getWithThemeValue('neutral-translucent-100-hover'),
    neutralTranslucentColor100Inverted: getWithThemeValue('neutral-translucent-100-inverted'),
    neutralTranslucentColor100InvertedHover: getWithThemeValue(
        'neutral-translucent-100-inverted-hover',
    ),
    neutralTranslucentColor100InvertedPress: getWithThemeValue(
        'neutral-translucent-100-inverted-press',
    ),
    neutralTranslucentColor100Press: getWithThemeValue('neutral-translucent-100-press'),
    neutralTranslucentColor1500Hover: getWithThemeValue('neutral-translucent-1500-hover'),
    neutralTranslucentColor1500InvertedHover: getWithThemeValue(
        'neutral-translucent-1500-inverted-hover',
    ),
    neutralTranslucentColor1500InvertedPress: getWithThemeValue(
        'neutral-translucent-1500-inverted-press',
    ),
    neutralTranslucentColor1500Press: getWithThemeValue('neutral-translucent-1500-press'),
    neutralTranslucentColor200: getWithThemeValue('neutral-translucent-200'),
    neutralTranslucentColor200Hover: getWithThemeValue('neutral-translucent-200-hover'),
    neutralTranslucentColor200Inverted: getWithThemeValue('neutral-translucent-200-inverted'),
    neutralTranslucentColor200InvertedHover: getWithThemeValue(
        'neutral-translucent-200-inverted-hover',
    ),
    neutralTranslucentColor200InvertedPress: getWithThemeValue(
        'neutral-translucent-200-inverted-press',
    ),
    neutralTranslucentColor200Press: getWithThemeValue('neutral-translucent-200-press'),
    neutralTranslucentColor300: getWithThemeValue('neutral-translucent-300'),
    neutralTranslucentColor300Hover: getWithThemeValue('neutral-translucent-300-hover'),
    neutralTranslucentColor300Inverted: getWithThemeValue('neutral-translucent-300-inverted'),
    neutralTranslucentColor300InvertedHover: getWithThemeValue(
        'neutral-translucent-300-inverted-hover',
    ),
    neutralTranslucentColor300InvertedPress: getWithThemeValue(
        'neutral-translucent-300-inverted-press',
    ),
    neutralTranslucentColor300Press: getWithThemeValue('neutral-translucent-300-press'),
    neutralTranslucentColor400: getWithThemeValue('neutral-translucent-400'),
    neutralTranslucentColor400Hover: getWithThemeValue('neutral-translucent-400-hover'),
    neutralTranslucentColor400Inverted: getWithThemeValue('neutral-translucent-400-inverted'),
    neutralTranslucentColor400InvertedHover: getWithThemeValue(
        'neutral-translucent-400-inverted-hover',
    ),
    neutralTranslucentColor400InvertedPress: getWithThemeValue(
        'neutral-translucent-400-inverted-press',
    ),
    neutralTranslucentColor400Press: getWithThemeValue('neutral-translucent-400-press'),
    neutralTranslucentColor500: getWithThemeValue('neutral-translucent-500'),
    neutralTranslucentColor500Hover: getWithThemeValue('neutral-translucent-500-hover'),
    neutralTranslucentColor500Inverted: getWithThemeValue('neutral-translucent-500-inverted'),
    neutralTranslucentColor500InvertedHover: getWithThemeValue(
        'neutral-translucent-500-inverted-hover',
    ),
    neutralTranslucentColor500InvertedPress: getWithThemeValue(
        'neutral-translucent-500-inverted-press',
    ),
    neutralTranslucentColor500Press: getWithThemeValue('neutral-translucent-500-press'),
    neutralTranslucentColor700: getWithThemeValue('neutral-translucent-700'),
    neutralTranslucentColor700Hover: getWithThemeValue('neutral-translucent-700-hover'),
    neutralTranslucentColor700Inverted: getWithThemeValue('neutral-translucent-700-inverted'),
    neutralTranslucentColor700InvertedHover: getWithThemeValue(
        'neutral-translucent-700-inverted-hover',
    ),
    neutralTranslucentColor700InvertedPress: getWithThemeValue(
        'neutral-translucent-700-inverted-press',
    ),
    neutralTranslucentColor700Press: getWithThemeValue('neutral-translucent-700-press'),
    overlayColorDefault: getWithThemeValue('overlay-default'),
    qualitativeDuocolorSetAColor1: getWithThemeValue('qualitative-duocolor-set-a-1'),
    qualitativeDuocolorSetAColor2: getWithThemeValue('qualitative-duocolor-set-a-2'),
    qualitativeDuocolorSetBColor1: getWithThemeValue('qualitative-duocolor-set-b-1'),
    qualitativeDuocolorSetBColor2: getWithThemeValue('qualitative-duocolor-set-b-2'),
    qualitativeDuocolorSetCColor1: getWithThemeValue('qualitative-duocolor-set-c-1'),
    qualitativeDuocolorSetCColor2: getWithThemeValue('qualitative-duocolor-set-c-2'),
    qualitativeDuocolorSetDColor1: getWithThemeValue('qualitative-duocolor-set-d-1'),
    qualitativeDuocolorSetDColor2: getWithThemeValue('qualitative-duocolor-set-d-2'),
    qualitativeDuocolorSetEColor1: getWithThemeValue('qualitative-duocolor-set-e-1'),
    qualitativeDuocolorSetEColor2: getWithThemeValue('qualitative-duocolor-set-e-2'),
    qualitativeDuocolorSetFColor1: getWithThemeValue('qualitative-duocolor-set-f-1'),
    qualitativeDuocolorSetFColor2: getWithThemeValue('qualitative-duocolor-set-f-2'),
    qualitativeDuocolorSetGColor1: getWithThemeValue('qualitative-duocolor-set-g-1'),
    qualitativeDuocolorSetGColor2: getWithThemeValue('qualitative-duocolor-set-g-2'),
    qualitativeFlexibleColor1: getWithThemeValue('qualitative-flexible-1'),
    qualitativeFlexibleColor10: getWithThemeValue('qualitative-flexible-10'),
    qualitativeFlexibleColor11: getWithThemeValue('qualitative-flexible-11'),
    qualitativeFlexibleColor12: getWithThemeValue('qualitative-flexible-12'),
    qualitativeFlexibleColor13: getWithThemeValue('qualitative-flexible-13'),
    qualitativeFlexibleColor14: getWithThemeValue('qualitative-flexible-14'),
    qualitativeFlexibleColor2: getWithThemeValue('qualitative-flexible-2'),
    qualitativeFlexibleColor3: getWithThemeValue('qualitative-flexible-3'),
    qualitativeFlexibleColor4: getWithThemeValue('qualitative-flexible-4'),
    qualitativeFlexibleColor5: getWithThemeValue('qualitative-flexible-5'),
    qualitativeFlexibleColor6: getWithThemeValue('qualitative-flexible-6'),
    qualitativeFlexibleColor7: getWithThemeValue('qualitative-flexible-7'),
    qualitativeFlexibleColor8: getWithThemeValue('qualitative-flexible-8'),
    qualitativeFlexibleColor9: getWithThemeValue('qualitative-flexible-9'),
    qualitativeMonocolorColorBlue: getWithThemeValue('qualitative-monocolor-blue'),
    qualitativeMonocolorColorGreen: getWithThemeValue('qualitative-monocolor-green'),
    qualitativeMonocolorColorIndigo: getWithThemeValue('qualitative-monocolor-indigo'),
    qualitativeMonocolorColorMagenta: getWithThemeValue('qualitative-monocolor-magenta'),
    qualitativeMonocolorColorOrange: getWithThemeValue('qualitative-monocolor-orange'),
    qualitativeMonocolorColorPistachio: getWithThemeValue('qualitative-monocolor-pistachio'),
    qualitativeMonocolorColorRed: getWithThemeValue('qualitative-monocolor-red'),
    qualitativeMonocolorColorTeal: getWithThemeValue('qualitative-monocolor-teal'),
    qualitativeMonocolorColorYellow: getWithThemeValue('qualitative-monocolor-yellow'),
    qualitativeTetracolorSetAColor1: getWithThemeValue('qualitative-tetracolor-set-a-1'),
    qualitativeTetracolorSetAColor2: getWithThemeValue('qualitative-tetracolor-set-a-2'),
    qualitativeTetracolorSetAColor3: getWithThemeValue('qualitative-tetracolor-set-a-3'),
    qualitativeTetracolorSetAColor4: getWithThemeValue('qualitative-tetracolor-set-a-4'),
    qualitativeTetracolorSetBColor1: getWithThemeValue('qualitative-tetracolor-set-b-1'),
    qualitativeTetracolorSetBColor2: getWithThemeValue('qualitative-tetracolor-set-b-2'),
    qualitativeTetracolorSetBColor3: getWithThemeValue('qualitative-tetracolor-set-b-3'),
    qualitativeTetracolorSetBColor4: getWithThemeValue('qualitative-tetracolor-set-b-4'),
    qualitativeTetracolorSetCColor1: getWithThemeValue('qualitative-tetracolor-set-c-1'),
    qualitativeTetracolorSetCColor2: getWithThemeValue('qualitative-tetracolor-set-c-2'),
    qualitativeTetracolorSetCColor3: getWithThemeValue('qualitative-tetracolor-set-c-3'),
    qualitativeTetracolorSetCColor4: getWithThemeValue('qualitative-tetracolor-set-c-4'),
    qualitativeTricolorSetAColor1: getWithThemeValue('qualitative-tricolor-set-a-1'),
    qualitativeTricolorSetAColor2: getWithThemeValue('qualitative-tricolor-set-a-2'),
    qualitativeTricolorSetAColor3: getWithThemeValue('qualitative-tricolor-set-a-3'),
    qualitativeTricolorSetBColor1: getWithThemeValue('qualitative-tricolor-set-b-1'),
    qualitativeTricolorSetBColor2: getWithThemeValue('qualitative-tricolor-set-b-2'),
    qualitativeTricolorSetBColor3: getWithThemeValue('qualitative-tricolor-set-b-3'),
    qualitativeTricolorSetCColor1: getWithThemeValue('qualitative-tricolor-set-c-1'),
    qualitativeTricolorSetCColor2: getWithThemeValue('qualitative-tricolor-set-c-2'),
    qualitativeTricolorSetCColor3: getWithThemeValue('qualitative-tricolor-set-c-3'),
    qualitativeTricolorSetDColor1: getWithThemeValue('qualitative-tricolor-set-d-1'),
    qualitativeTricolorSetDColor2: getWithThemeValue('qualitative-tricolor-set-d-2'),
    qualitativeTricolorSetDColor3: getWithThemeValue('qualitative-tricolor-set-d-3'),
    qualitativeTricolorSetEColor1: getWithThemeValue('qualitative-tricolor-set-e-1'),
    qualitativeTricolorSetEColor2: getWithThemeValue('qualitative-tricolor-set-e-2'),
    qualitativeTricolorSetEColor3: getWithThemeValue('qualitative-tricolor-set-e-3'),
    sequentialBlueColor1: getWithThemeValue('sequential-blue-1'),
    sequentialBlueColor2: getWithThemeValue('sequential-blue-2'),
    sequentialBlueColor3: getWithThemeValue('sequential-blue-3'),
    sequentialBlueColor4: getWithThemeValue('sequential-blue-4'),
    sequentialBlueColor5: getWithThemeValue('sequential-blue-5'),
    sequentialBlueColor6: getWithThemeValue('sequential-blue-6'),
    sequentialBlueColor7: getWithThemeValue('sequential-blue-7'),
    sequentialCyanColor1: getWithThemeValue('sequential-cyan-1'),
    sequentialCyanColor2: getWithThemeValue('sequential-cyan-2'),
    sequentialCyanColor3: getWithThemeValue('sequential-cyan-3'),
    sequentialCyanColor4: getWithThemeValue('sequential-cyan-4'),
    sequentialCyanColor5: getWithThemeValue('sequential-cyan-5'),
    sequentialCyanColor6: getWithThemeValue('sequential-cyan-6'),
    sequentialCyanColor7: getWithThemeValue('sequential-cyan-7'),
    sequentialFuchsiaColor1: getWithThemeValue('sequential-fuchsia-1'),
    sequentialFuchsiaColor2: getWithThemeValue('sequential-fuchsia-2'),
    sequentialFuchsiaColor3: getWithThemeValue('sequential-fuchsia-3'),
    sequentialFuchsiaColor4: getWithThemeValue('sequential-fuchsia-4'),
    sequentialFuchsiaColor5: getWithThemeValue('sequential-fuchsia-5'),
    sequentialFuchsiaColor6: getWithThemeValue('sequential-fuchsia-6'),
    sequentialFuchsiaColor7: getWithThemeValue('sequential-fuchsia-7'),
    sequentialGreenColor1: getWithThemeValue('sequential-green-1'),
    sequentialGreenColor2: getWithThemeValue('sequential-green-2'),
    sequentialGreenColor3: getWithThemeValue('sequential-green-3'),
    sequentialGreenColor4: getWithThemeValue('sequential-green-4'),
    sequentialGreenColor5: getWithThemeValue('sequential-green-5'),
    sequentialGreenColor6: getWithThemeValue('sequential-green-6'),
    sequentialGreenColor7: getWithThemeValue('sequential-green-7'),
    sequentialIndigoColor1: getWithThemeValue('sequential-indigo-1'),
    sequentialIndigoColor2: getWithThemeValue('sequential-indigo-2'),
    sequentialIndigoColor3: getWithThemeValue('sequential-indigo-3'),
    sequentialIndigoColor4: getWithThemeValue('sequential-indigo-4'),
    sequentialIndigoColor5: getWithThemeValue('sequential-indigo-5'),
    sequentialIndigoColor6: getWithThemeValue('sequential-indigo-6'),
    sequentialIndigoColor7: getWithThemeValue('sequential-indigo-7'),
    sequentialJungleColor1: getWithThemeValue('sequential-jungle-1'),
    sequentialJungleColor2: getWithThemeValue('sequential-jungle-2'),
    sequentialJungleColor3: getWithThemeValue('sequential-jungle-3'),
    sequentialJungleColor4: getWithThemeValue('sequential-jungle-4'),
    sequentialJungleColor5: getWithThemeValue('sequential-jungle-5'),
    sequentialJungleColor6: getWithThemeValue('sequential-jungle-6'),
    sequentialJungleColor7: getWithThemeValue('sequential-jungle-7'),
    sequentialMagentaColor1: getWithThemeValue('sequential-magenta-1'),
    sequentialMagentaColor2: getWithThemeValue('sequential-magenta-2'),
    sequentialMagentaColor3: getWithThemeValue('sequential-magenta-3'),
    sequentialMagentaColor4: getWithThemeValue('sequential-magenta-4'),
    sequentialMagentaColor5: getWithThemeValue('sequential-magenta-5'),
    sequentialMagentaColor6: getWithThemeValue('sequential-magenta-6'),
    sequentialMagentaColor7: getWithThemeValue('sequential-magenta-7'),
    sequentialOrangeColor1: getWithThemeValue('sequential-orange-1'),
    sequentialOrangeColor2: getWithThemeValue('sequential-orange-2'),
    sequentialOrangeColor3: getWithThemeValue('sequential-orange-3'),
    sequentialOrangeColor4: getWithThemeValue('sequential-orange-4'),
    sequentialOrangeColor5: getWithThemeValue('sequential-orange-5'),
    sequentialOrangeColor6: getWithThemeValue('sequential-orange-6'),
    sequentialOrangeColor7: getWithThemeValue('sequential-orange-7'),
    sequentialPistachioColor1: getWithThemeValue('sequential-pistachio-1'),
    sequentialPistachioColor2: getWithThemeValue('sequential-pistachio-2'),
    sequentialPistachioColor3: getWithThemeValue('sequential-pistachio-3'),
    sequentialPistachioColor4: getWithThemeValue('sequential-pistachio-4'),
    sequentialPistachioColor5: getWithThemeValue('sequential-pistachio-5'),
    sequentialPistachioColor6: getWithThemeValue('sequential-pistachio-6'),
    sequentialPistachioColor7: getWithThemeValue('sequential-pistachio-7'),
    sequentialPurpleColor1: getWithThemeValue('sequential-purple-1'),
    sequentialPurpleColor2: getWithThemeValue('sequential-purple-2'),
    sequentialPurpleColor3: getWithThemeValue('sequential-purple-3'),
    sequentialPurpleColor4: getWithThemeValue('sequential-purple-4'),
    sequentialPurpleColor5: getWithThemeValue('sequential-purple-5'),
    sequentialPurpleColor6: getWithThemeValue('sequential-purple-6'),
    sequentialPurpleColor7: getWithThemeValue('sequential-purple-7'),
    sequentialRedColor1: getWithThemeValue('sequential-red-1'),
    sequentialRedColor2: getWithThemeValue('sequential-red-2'),
    sequentialRedColor3: getWithThemeValue('sequential-red-3'),
    sequentialRedColor4: getWithThemeValue('sequential-red-4'),
    sequentialRedColor5: getWithThemeValue('sequential-red-5'),
    sequentialRedColor6: getWithThemeValue('sequential-red-6'),
    sequentialRedColor7: getWithThemeValue('sequential-red-7'),
    sequentialTealColor1: getWithThemeValue('sequential-teal-1'),
    sequentialTealColor2: getWithThemeValue('sequential-teal-2'),
    sequentialTealColor3: getWithThemeValue('sequential-teal-3'),
    sequentialTealColor4: getWithThemeValue('sequential-teal-4'),
    sequentialTealColor5: getWithThemeValue('sequential-teal-5'),
    sequentialTealColor6: getWithThemeValue('sequential-teal-6'),
    sequentialTealColor7: getWithThemeValue('sequential-teal-7'),
    specialBackgroundColorComponent: getWithThemeValue('specialbg-component'),
    specialBackgroundColorComponentInverted: getWithThemeValue('specialbg-component-inverted'),
    specialBackgroundColorNulled: getWithThemeValue('specialbg-nulled'),
    specialBackgroundColorOverlay: getWithThemeValue('specialbg-overlay'),
    specialBackgroundColorOverlayFallback: getWithThemeValue('specialbg-overlay-fallback'),
    specialBackgroundColorPrimaryGrouped: getWithThemeValue('specialbg-primary-grouped'),
    specialBackgroundColorSecondaryGrouped: getWithThemeValue('specialbg-secondary-grouped'),
    specialBackgroundColorSecondaryTransparent: getWithThemeValue(
        'specialbg-secondary-transparent',
    ),
    specialBackgroundColorSecondaryTransparentInverted: getWithThemeValue(
        'specialbg-secondary-transparent-inverted',
    ),
    specialBackgroundColorTertiaryGrouped: getWithThemeValue('specialbg-tertiary-grouped'),
    specialBackgroundColorTertiaryTransparent: getWithThemeValue('specialbg-tertiary-transparent'),
    specialBackgroundColorTertiaryTransparentInverted: getWithThemeValue(
        'specialbg-tertiary-transparent-inverted',
    ),
    staticAccentColorPrimary: getWithoutThemeValue('static-accent-primary'),
    staticAccentColorPrimaryHover: getWithoutThemeValue('static-accent-primary-hover'),
    staticAccentColorPrimaryInverted: getWithoutThemeValue('static-accent-primary-inverted'),
    staticAccentColorPrimaryInvertedHover: getWithoutThemeValue(
        'static-accent-primary-inverted-hover',
    ),
    staticAccentColorPrimaryInvertedPress: getWithoutThemeValue(
        'static-accent-primary-inverted-press',
    ),
    staticAccentColorPrimaryPress: getWithoutThemeValue('static-accent-primary-press'),
    staticAccentColorSecondary: getWithoutThemeValue('static-accent-secondary'),
    staticAccentColorSecondaryHover: getWithoutThemeValue('static-accent-secondary-hover'),
    staticAccentColorSecondaryInverted: getWithoutThemeValue('static-accent-secondary-inverted'),
    staticAccentColorSecondaryInvertedHover: getWithoutThemeValue(
        'static-accent-secondary-inverted-hover',
    ),
    staticAccentColorSecondaryInvertedPress: getWithoutThemeValue(
        'static-accent-secondary-inverted-press',
    ),
    staticAccentColorSecondaryPress: getWithoutThemeValue('static-accent-secondary-press'),
    staticBackgroundColorAccent: getWithoutThemeValue('static-bg-accent'),
    staticBackgroundColorDark: getWithoutThemeValue('static-bg-dark'),
    staticBackgroundColorLight: getWithoutThemeValue('static-bg-light'),
    staticBackgroundColorNeutralDark: getWithoutThemeValue('static-bg-neutral-dark'),
    staticBackgroundColorNeutralLight: getWithoutThemeValue('static-bg-neutral-light'),
    staticBackgroundColorPrimaryDark: getWithoutThemeValue('static-bg-primary-dark'),
    staticBackgroundColorPrimaryLight: getWithoutThemeValue('static-bg-primary-light'),
    staticBackgroundColorQuaternaryDark: getWithoutThemeValue('static-bg-quaternary-dark'),
    staticBackgroundColorQuaternaryLight: getWithoutThemeValue('static-bg-quaternary-light'),
    staticBackgroundColorSecondaryDark: getWithoutThemeValue('static-bg-secondary-dark'),
    staticBackgroundColorSecondaryLight: getWithoutThemeValue('static-bg-secondary-light'),
    staticBackgroundColorTertiaryDark: getWithoutThemeValue('static-bg-tertiary-dark'),
    staticBackgroundColorTertiaryLight: getWithoutThemeValue('static-bg-tertiary-light'),
    staticBorderColorAccent: getWithoutThemeValue('static-border-accent'),
    staticGraphicColorAccent: getWithoutThemeValue('static-graphic-accent'),
    staticGraphicColorAmethyst: getWithoutThemeValue('static-graphic-amethyst'),
    staticGraphicColorBlackberry: getWithoutThemeValue('static-graphic-blackberry'),
    staticGraphicColorBlueMaya: getWithoutThemeValue('static-graphic-blue-maya'),
    staticGraphicColorBlueMoody: getWithoutThemeValue('static-graphic-blue-moody'),
    staticGraphicColorBotticelli: getWithoutThemeValue('static-graphic-botticelli'),
    staticGraphicColorBurntSienna: getWithoutThemeValue('static-graphic-burnt-sienna'),
    staticGraphicColorCarrot: getWithoutThemeValue('static-graphic-carrot'),
    staticGraphicColorChick: getWithoutThemeValue('static-graphic-chick'),
    staticGraphicColorDark: getWithoutThemeValue('static-graphic-dark'),
    staticGraphicColorFunBlue: getWithoutThemeValue('static-graphic-fun-blue'),
    staticGraphicColorGallery: getWithoutThemeValue('static-graphic-gallery'),
    staticGraphicColorGreenJungle: getWithoutThemeValue('static-graphic-green-jungle'),
    staticGraphicColorJaffaLight: getWithoutThemeValue('static-graphic-jaffa-light'),
    staticGraphicColorLavender: getWithoutThemeValue('static-graphic-lavender'),
    staticGraphicColorLight: getWithoutThemeValue('static-graphic-light'),
    staticGraphicColorMaya: getWithoutThemeValue('static-graphic-maya'),
    staticGraphicColorOlive: getWithoutThemeValue('static-graphic-olive'),
    staticGraphicColorOlivine: getWithoutThemeValue('static-graphic-olivine'),
    staticGraphicColorPeach: getWithoutThemeValue('static-graphic-peach'),
    staticGraphicColorPermission: getWithoutThemeValue('static-graphic-permission'),
    staticGraphicColorPewter: getWithoutThemeValue('static-graphic-pewter'),
    staticGraphicColorRaspberry: getWithoutThemeValue('static-graphic-raspberry'),
    staticGraphicColorSalomie: getWithoutThemeValue('static-graphic-salomie'),
    staticGraphicColorSand: getWithoutThemeValue('static-graphic-sand'),
    staticGraphicColorSeawater: getWithoutThemeValue('static-graphic-seawater'),
    staticGraphicColorSky: getWithoutThemeValue('static-graphic-sky'),
    staticGraphicColorSoftPeach: getWithoutThemeValue('static-graphic-soft-peach'),
    staticGraphicColorSolitude: getWithoutThemeValue('static-graphic-solitude'),
    staticGraphicColorStrawberry: getWithoutThemeValue('static-graphic-strawberry'),
    staticGraphicColorSundust: getWithoutThemeValue('static-graphic-sundust'),
    staticGraphicColorValencia: getWithoutThemeValue('static-graphic-valencia'),
    staticLocalColorLightBlue: getWithoutThemeValue('static-local-light-blue'),
    staticNeutralColor0: getWithoutThemeValue('static-neutral-0'),
    staticNeutralColor0Hover: getWithoutThemeValue('static-neutral-0-hover'),
    staticNeutralColor0Inverted: getWithoutThemeValue('static-neutral-0-inverted'),
    staticNeutralColor0InvertedHover: getWithoutThemeValue('static-neutral-0-inverted-hover'),
    staticNeutralColor0InvertedPress: getWithoutThemeValue('static-neutral-0-inverted-press'),
    staticNeutralColor0Press: getWithoutThemeValue('static-neutral-0-press'),
    staticNeutralColor100: getWithoutThemeValue('static-neutral-100'),
    staticNeutralColor100Hover: getWithoutThemeValue('static-neutral-100-hover'),
    staticNeutralColor100Inverted: getWithoutThemeValue('static-neutral-100-inverted'),
    staticNeutralColor100InvertedHover: getWithoutThemeValue('static-neutral-100-inverted-hover'),
    staticNeutralColor100InvertedPress: getWithoutThemeValue('static-neutral-100-inverted-press'),
    staticNeutralColor100Press: getWithoutThemeValue('static-neutral-100-press'),
    staticNeutralColor1500: getWithoutThemeValue('static-neutral-1500'),
    staticNeutralColor1500Hover: getWithoutThemeValue('static-neutral-1500-hover'),
    staticNeutralColor1500Inverted: getWithoutThemeValue('static-neutral-1500-inverted'),
    staticNeutralColor1500InvertedHover: getWithoutThemeValue('static-neutral-1500-inverted-hover'),
    staticNeutralColor1500InvertedPress: getWithoutThemeValue('static-neutral-1500-inverted-press'),
    staticNeutralColor1500Press: getWithoutThemeValue('static-neutral-1500-press'),
    staticNeutralColor200: getWithoutThemeValue('static-neutral-200'),
    staticNeutralColor200Hover: getWithoutThemeValue('static-neutral-200-hover'),
    staticNeutralColor200Inverted: getWithoutThemeValue('static-neutral-200-inverted'),
    staticNeutralColor200InvertedHover: getWithoutThemeValue('static-neutral-200-inverted-hover'),
    staticNeutralColor200InvertedPress: getWithoutThemeValue('static-neutral-200-inverted-press'),
    staticNeutralColor200Press: getWithoutThemeValue('static-neutral-200-press'),
    staticNeutralColor300: getWithoutThemeValue('static-neutral-300'),
    staticNeutralColor300Hover: getWithoutThemeValue('static-neutral-300-hover'),
    staticNeutralColor300Inverted: getWithoutThemeValue('static-neutral-300-inverted'),
    staticNeutralColor300InvertedHover: getWithoutThemeValue('static-neutral-300-inverted-hover'),
    staticNeutralColor300InvertedPress: getWithoutThemeValue('static-neutral-300-inverted-press'),
    staticNeutralColor300Press: getWithoutThemeValue('static-neutral-300-press'),
    staticNeutralColor400: getWithoutThemeValue('static-neutral-400'),
    staticNeutralColor400Hover: getWithoutThemeValue('static-neutral-400-hover'),
    staticNeutralColor400Inverted: getWithoutThemeValue('static-neutral-400-inverted'),
    staticNeutralColor400InvertedHover: getWithoutThemeValue('static-neutral-400-inverted-hover'),
    staticNeutralColor400InvertedPress: getWithoutThemeValue('static-neutral-400-inverted-press'),
    staticNeutralColor400Press: getWithoutThemeValue('static-neutral-400-press'),
    staticNeutralColor500: getWithoutThemeValue('static-neutral-500'),
    staticNeutralColor500Hover: getWithoutThemeValue('static-neutral-500-hover'),
    staticNeutralColor500Inverted: getWithoutThemeValue('static-neutral-500-inverted'),
    staticNeutralColor500InvertedHover: getWithoutThemeValue('static-neutral-500-inverted-hover'),
    staticNeutralColor500InvertedPress: getWithoutThemeValue('static-neutral-500-inverted-press'),
    staticNeutralColor500Press: getWithoutThemeValue('static-neutral-500-press'),
    staticNeutralColor700: getWithoutThemeValue('static-neutral-700'),
    staticNeutralColor700Hover: getWithoutThemeValue('static-neutral-700-hover'),
    staticNeutralColor700Inverted: getWithoutThemeValue('static-neutral-700-inverted'),
    staticNeutralColor700InvertedHover: getWithoutThemeValue('static-neutral-700-inverted-hover'),
    staticNeutralColor700InvertedPress: getWithoutThemeValue('static-neutral-700-inverted-press'),
    staticNeutralColor700Press: getWithoutThemeValue('static-neutral-700-press'),
    staticNeutralTranslucentColor0: getWithoutThemeValue('static-neutral-translucent-0'),
    staticNeutralTranslucentColor0Hover: getWithoutThemeValue('static-neutral-translucent-0-hover'),
    staticNeutralTranslucentColor0Inverted: getWithoutThemeValue(
        'static-neutral-translucent-0-inverted',
    ),
    staticNeutralTranslucentColor0InvertedHover: getWithoutThemeValue(
        'static-neutral-translucent-0-inverted-hover',
    ),
    staticNeutralTranslucentColor0InvertedPress: getWithoutThemeValue(
        'static-neutral-translucent-0-inverted-press',
    ),
    staticNeutralTranslucentColor0Press: getWithoutThemeValue('static-neutral-translucent-0-press'),
    staticNeutralTranslucentColor100: getWithoutThemeValue('static-neutral-translucent-100'),
    staticNeutralTranslucentColor100Hover: getWithoutThemeValue(
        'static-neutral-translucent-100-hover',
    ),
    staticNeutralTranslucentColor100Inverted: getWithoutThemeValue(
        'static-neutral-translucent-100-inverted',
    ),
    staticNeutralTranslucentColor100InvertedHover: getWithoutThemeValue(
        'static-neutral-translucent-100-inverted-hover',
    ),
    staticNeutralTranslucentColor100InvertedPress: getWithoutThemeValue(
        'static-neutral-translucent-100-inverted-press',
    ),
    staticNeutralTranslucentColor100Press: getWithoutThemeValue(
        'static-neutral-translucent-100-press',
    ),

    staticNeutralTranslucentColor1500Hover: getWithoutThemeValue(
        'static-neutral-translucent-1500-hover',
    ),
    staticNeutralTranslucentColor1500InvertedHover: getWithoutThemeValue(
        'static-neutral-translucent-1500-inverted-hover',
    ),
    staticNeutralTranslucentColor1500InvertedPress: getWithoutThemeValue(
        'static-neutral-translucent-1500-inverted-press',
    ),
    staticNeutralTranslucentColor1500Press: getWithoutThemeValue(
        'static-neutral-translucent-1500-press',
    ),
    staticNeutralTranslucentColor200: getWithoutThemeValue('static-neutral-translucent-200'),
    staticNeutralTranslucentColor200Hover: getWithoutThemeValue(
        'static-neutral-translucent-200-hover',
    ),
    staticNeutralTranslucentColor200Inverted: getWithoutThemeValue(
        'static-neutral-translucent-200-inverted',
    ),
    staticNeutralTranslucentColor200InvertedHover: getWithoutThemeValue(
        'static-neutral-translucent-200-inverted-hover',
    ),
    staticNeutralTranslucentColor200InvertedPress: getWithoutThemeValue(
        'static-neutral-translucent-200-inverted-press',
    ),
    staticNeutralTranslucentColor200Press: getWithoutThemeValue(
        'static-neutral-translucent-200-press',
    ),
    staticNeutralTranslucentColor300: getWithoutThemeValue('static-neutral-translucent-300'),
    staticNeutralTranslucentColor300Hover: getWithoutThemeValue(
        'static-neutral-translucent-300-hover',
    ),
    staticNeutralTranslucentColor300Inverted: getWithoutThemeValue(
        'static-neutral-translucent-300-inverted',
    ),
    staticNeutralTranslucentColor300InvertedHover: getWithoutThemeValue(
        'static-neutral-translucent-300-inverted-hover',
    ),
    staticNeutralTranslucentColor300InvertedPress: getWithoutThemeValue(
        'static-neutral-translucent-300-inverted-press',
    ),
    staticNeutralTranslucentColor300Press: getWithoutThemeValue(
        'static-neutral-translucent-300-press',
    ),
    staticNeutralTranslucentColor400: getWithoutThemeValue('static-neutral-translucent-400'),
    staticNeutralTranslucentColor400Hover: getWithoutThemeValue(
        'static-neutral-translucent-400-hover',
    ),
    staticNeutralTranslucentColor400Inverted: getWithoutThemeValue(
        'static-neutral-translucent-400-inverted',
    ),
    staticNeutralTranslucentColor400InvertedHover: getWithoutThemeValue(
        'static-neutral-translucent-400-inverted-hover',
    ),
    staticNeutralTranslucentColor400InvertedPress: getWithoutThemeValue(
        'static-neutral-translucent-400-inverted-press',
    ),
    staticNeutralTranslucentColor400Press: getWithoutThemeValue(
        'static-neutral-translucent-400-press',
    ),
    staticNeutralTranslucentColor500: getWithoutThemeValue('static-neutral-translucent-500'),
    staticNeutralTranslucentColor500Hover: getWithoutThemeValue(
        'static-neutral-translucent-500-hover',
    ),
    staticNeutralTranslucentColor500Inverted: getWithoutThemeValue(
        'static-neutral-translucent-500-inverted',
    ),
    staticNeutralTranslucentColor500InvertedHover: getWithoutThemeValue(
        'static-neutral-translucent-500-inverted-hover',
    ),
    staticNeutralTranslucentColor500InvertedPress: getWithoutThemeValue(
        'static-neutral-translucent-500-inverted-press',
    ),
    staticNeutralTranslucentColor500Press: getWithoutThemeValue(
        'static-neutral-translucent-500-press',
    ),
    staticNeutralTranslucentColor700: getWithoutThemeValue('static-neutral-translucent-700'),
    staticNeutralTranslucentColor700Hover: getWithoutThemeValue(
        'static-neutral-translucent-700-hover',
    ),
    staticNeutralTranslucentColor700Inverted: getWithoutThemeValue(
        'static-neutral-translucent-700-inverted',
    ),
    staticNeutralTranslucentColor700InvertedHover: getWithoutThemeValue(
        'static-neutral-translucent-700-inverted-hover',
    ),
    staticNeutralTranslucentColor700InvertedPress: getWithoutThemeValue(
        'static-neutral-translucent-700-inverted-press',
    ),
    staticNeutralTranslucentColor700Press: getWithoutThemeValue(
        'static-neutral-translucent-700-press',
    ),
    staticOverlayColorBlackHigh: getWithoutThemeValue('static-overlay-black-high'),
    staticOverlayColorBlackLow: getWithoutThemeValue('static-overlay-black-low'),
    staticOverlayColorBlackNormal: getWithoutThemeValue('static-overlay-black-normal'),
    staticOverlayColorBlackXhigh: getWithoutThemeValue('static-overlay-black-xhigh'),
    staticOverlayColorBlackXlow: getWithoutThemeValue('static-overlay-black-xlow'),
    staticOverlayColorWhiteHigh: getWithoutThemeValue('static-overlay-white-high'),
    staticOverlayColorWhiteLow: getWithoutThemeValue('static-overlay-white-low'),
    staticOverlayColorWhiteNormal: getWithoutThemeValue('static-overlay-white-normal'),
    staticOverlayColorWhiteXhigh: getWithoutThemeValue('static-overlay-white-xhigh'),
    staticOverlayColorWhiteXlow: getWithoutThemeValue('static-overlay-white-xlow'),
    staticPfmCustomColorBlue: getWithoutThemeValue('static-pfm-custom-blue'),
    staticPfmCustomColorCyan: getWithoutThemeValue('static-pfm-custom-cyan'),
    staticPfmCustomColorIndigo: getWithoutThemeValue('static-pfm-custom-indigo'),
    staticPfmCustomColorJungle: getWithoutThemeValue('static-pfm-custom-jungle'),
    staticPfmCustomColorMagenta: getWithoutThemeValue('static-pfm-custom-magenta'),
    staticPfmCustomColorOrange: getWithoutThemeValue('static-pfm-custom-orange'),
    staticPfmCustomColorPistachio: getWithoutThemeValue('static-pfm-custom-pistachio'),
    staticPfmCustomColorPurple: getWithoutThemeValue('static-pfm-custom-purple'),
    staticPfmCustomColorRed: getWithoutThemeValue('static-pfm-custom-red'),
    staticPfmCustomColorYellow: getWithoutThemeValue('static-pfm-custom-yellow'),
    staticPfmSystemColorAcrux: getWithoutThemeValue('static-pfm-system-acrux'),
    staticPfmSystemColorAlcor: getWithoutThemeValue('static-pfm-system-alcor'),
    staticPfmSystemColorAldebaran: getWithoutThemeValue('static-pfm-system-aldebaran'),
    staticPfmSystemColorAndromeda: getWithoutThemeValue('static-pfm-system-andromeda'),
    staticPfmSystemColorApollo: getWithoutThemeValue('static-pfm-system-apollo'),
    staticPfmSystemColorAtlas: getWithoutThemeValue('static-pfm-system-atlas'),
    staticPfmSystemColorBetelgeuse: getWithoutThemeValue('static-pfm-system-betelgeuse'),
    staticPfmSystemColorCapella: getWithoutThemeValue('static-pfm-system-capella'),
    staticPfmSystemColorCarmenta: getWithoutThemeValue('static-pfm-system-carmenta'),
    staticPfmSystemColorConcordia: getWithoutThemeValue('static-pfm-system-concordia'),
    staticPfmSystemColorCupid: getWithoutThemeValue('static-pfm-system-cupid'),
    staticPfmSystemColorElectra: getWithoutThemeValue('static-pfm-system-electra'),
    staticPfmSystemColorEnif: getWithoutThemeValue('static-pfm-system-enif'),
    staticPfmSystemColorFides: getWithoutThemeValue('static-pfm-system-fides'),
    staticPfmSystemColorGalaxy: getWithoutThemeValue('static-pfm-system-galaxy'),
    staticPfmSystemColorHelix: getWithoutThemeValue('static-pfm-system-helix'),
    staticPfmSystemColorHubble: getWithoutThemeValue('static-pfm-system-hubble'),
    staticPfmSystemColorJupiter: getWithoutThemeValue('static-pfm-system-jupiter'),
    staticPfmSystemColorKaus: getWithoutThemeValue('static-pfm-system-kaus'),
    staticPfmSystemColorKepler: getWithoutThemeValue('static-pfm-system-kepler'),
    staticPfmSystemColorMaia: getWithoutThemeValue('static-pfm-system-maia'),
    staticPfmSystemColorMars: getWithoutThemeValue('static-pfm-system-mars'),
    staticPfmSystemColorMeissa: getWithoutThemeValue('static-pfm-system-meissa'),
    staticPfmSystemColorMercury: getWithoutThemeValue('static-pfm-system-mercury'),
    staticPfmSystemColorMira: getWithoutThemeValue('static-pfm-system-mira'),
    staticPfmSystemColorMizar: getWithoutThemeValue('static-pfm-system-mizar'),
    staticPfmSystemColorNebula: getWithoutThemeValue('static-pfm-system-nebula'),
    staticPfmSystemColorNuma: getWithoutThemeValue('static-pfm-system-numa'),
    staticPfmSystemColorOrcus: getWithoutThemeValue('static-pfm-system-orcus'),
    staticPfmSystemColorOrion: getWithoutThemeValue('static-pfm-system-orion'),
    staticPfmSystemColorPluto: getWithoutThemeValue('static-pfm-system-pluto'),
    staticPfmSystemColorProserpina: getWithoutThemeValue('static-pfm-system-proserpina'),
    staticPfmSystemColorProxima: getWithoutThemeValue('static-pfm-system-proxima'),
    staticPfmSystemColorRegulus: getWithoutThemeValue('static-pfm-system-regulus'),
    staticPfmSystemColorRigel: getWithoutThemeValue('static-pfm-system-rigel'),
    staticPfmSystemColorSaturn: getWithoutThemeValue('static-pfm-system-saturn'),
    staticPfmSystemColorSirius: getWithoutThemeValue('static-pfm-system-sirius'),
    staticPfmSystemColorSpica: getWithoutThemeValue('static-pfm-system-spica'),
    staticPfmSystemColorSun: getWithoutThemeValue('static-pfm-system-sun'),
    staticPfmSystemColorTars: getWithoutThemeValue('static-pfm-system-tars'),
    staticPfmSystemColorTerra: getWithoutThemeValue('static-pfm-system-terra'),
    staticPfmSystemColorTriton: getWithoutThemeValue('static-pfm-system-triton'),
    staticPfmSystemColorUranus: getWithoutThemeValue('static-pfm-system-uranus'),
    staticPfmSystemColorVega: getWithoutThemeValue('static-pfm-system-vega'),
    staticPfmSystemColorVenus: getWithoutThemeValue('static-pfm-system-venus'),
    staticPfmSystemColorVoyager: getWithoutThemeValue('static-pfm-system-voyager'),
    staticPfmSystemColorVulcan: getWithoutThemeValue('static-pfm-system-vulcan'),
    staticPfmSystemColorWebb: getWithoutThemeValue('static-pfm-system-webb'),
    staticPfmSystemColorWezen: getWithoutThemeValue('static-pfm-system-wezen'),
    staticPfmSystemColorZwicky: getWithoutThemeValue('static-pfm-system-zwicky'),
    staticStatusColorAttention: getWithoutThemeValue('static-status-attention'),
    staticStatusColorAttentionInverted: getWithoutThemeValue('static-status-attention-inverted'),
    staticStatusColorBlue: getWithoutThemeValue('static-status-blue'),
    staticStatusColorGreen: getWithoutThemeValue('static-status-green'),
    staticStatusColorGrey: getWithoutThemeValue('static-status-grey'),
    staticStatusColorInfo: getWithoutThemeValue('static-status-info'),
    staticStatusColorInfoInverted: getWithoutThemeValue('static-status-info-inverted'),
    staticStatusColorNegative: getWithoutThemeValue('static-status-negative'),
    staticStatusColorNegativeInverted: getWithoutThemeValue('static-status-negative-inverted'),
    staticStatusColorOrange: getWithoutThemeValue('static-status-orange'),
    staticStatusColorPositive: getWithoutThemeValue('static-status-positive'),
    staticStatusColorPositiveInverted: getWithoutThemeValue('static-status-positive-inverted'),
    staticStatusColorPurple: getWithoutThemeValue('static-status-purple'),
    staticStatusColorRed: getWithoutThemeValue('static-status-red'),
    staticStatusColorTeal: getWithoutThemeValue('static-status-teal'),
    staticStatusMutedAltColorAttention: getWithoutThemeValue('static-status-muted-alt-attention'),
    staticStatusMutedAltColorAttentionInverted: getWithoutThemeValue(
        'static-status-muted-alt-attention-inverted',
    ),
    staticStatusMutedAltColorInfo: getWithoutThemeValue('static-status-muted-alt-info'),
    staticStatusMutedAltColorInfoInverted: getWithoutThemeValue(
        'static-status-muted-alt-info-inverted',
    ),
    staticStatusMutedAltColorNegative: getWithoutThemeValue('static-status-muted-alt-negative'),
    staticStatusMutedAltColorNegativeInverted: getWithoutThemeValue(
        'static-status-muted-alt-negative-inverted',
    ),
    staticStatusMutedAltColorPositive: getWithoutThemeValue('static-status-muted-alt-positive'),
    staticStatusMutedAltColorPositiveInverted: getWithoutThemeValue(
        'static-status-muted-alt-positive-inverted',
    ),
    staticStatusMutedColorAttention: getWithoutThemeValue('static-status-muted-attention'),
    staticStatusMutedColorAttentionInverted: getWithoutThemeValue(
        'static-status-muted-attention-inverted',
    ),
    staticStatusMutedColorInfo: getWithoutThemeValue('static-status-muted-info'),
    staticStatusMutedColorInfoInverted: getWithoutThemeValue('static-status-muted-info-inverted'),
    staticStatusMutedColorNegative: getWithoutThemeValue('static-status-muted-negative'),
    staticStatusMutedColorNegativeInverted: getWithoutThemeValue(
        'static-status-muted-negative-inverted',
    ),
    staticStatusMutedColorPositive: getWithoutThemeValue('static-status-muted-positive'),
    staticStatusMutedColorPositiveInverted: getWithoutThemeValue(
        'static-status-muted-positive-inverted',
    ),
    staticTextColorAccent: getWithoutThemeValue('static-text-accent'),
    staticTextColorAttention: getWithoutThemeValue('static-text-attention'),
    staticTextColorAttentionHover: getWithoutThemeValue('static-text-attention-hover'),
    staticTextColorAttentionInverted: getWithoutThemeValue('static-text-attention-inverted'),
    staticTextColorAttentionInvertedHover: getWithoutThemeValue(
        'static-text-attention-inverted-hover',
    ),
    staticTextColorAttentionInvertedPress: getWithoutThemeValue(
        'static-text-attention-inverted-press',
    ),
    staticTextColorAttentionPress: getWithoutThemeValue('static-text-attention-press'),
    staticTextColorInfo: getWithoutThemeValue('static-text-info'),
    staticTextColorInfoHover: getWithoutThemeValue('static-text-info-hover'),
    staticTextColorInfoInverted: getWithoutThemeValue('static-text-info-inverted'),
    staticTextColorInfoInvertedHover: getWithoutThemeValue('static-text-info-inverted-hover'),
    staticTextColorInfoInvertedPress: getWithoutThemeValue('static-text-info-inverted-press'),
    staticTextColorInfoPress: getWithoutThemeValue('static-text-info-press'),
    staticTextColorNegative: getWithoutThemeValue('static-text-negative'),
    staticTextColorNegativeHover: getWithoutThemeValue('static-text-negative-hover'),
    staticTextColorNegativeInverted: getWithoutThemeValue('static-text-negative-inverted'),
    staticTextColorNegativeInvertedHover: getWithoutThemeValue(
        'static-text-negative-inverted-hover',
    ),
    staticTextColorNegativeInvertedPress: getWithoutThemeValue(
        'static-text-negative-inverted-press',
    ),
    staticTextColorNegativePress: getWithoutThemeValue('static-text-negative-press'),
    staticTextColorPositive: getWithoutThemeValue('static-text-positive'),
    staticTextColorPositiveHover: getWithoutThemeValue('static-text-positive-hover'),
    staticTextColorPositiveInverted: getWithoutThemeValue('static-text-positive-inverted'),
    staticTextColorPositiveInvertedHover: getWithoutThemeValue(
        'static-text-positive-inverted-hover',
    ),
    staticTextColorPositiveInvertedPress: getWithoutThemeValue(
        'static-text-positive-inverted-press',
    ),
    staticTextColorPositivePress: getWithoutThemeValue('static-text-positive-press'),
    staticTextColorPrimary: getWithoutThemeValue('static-text-primary'),
    staticTextColorPrimaryDark: getWithoutThemeValue('static-text-primary-dark'),
    staticTextColorPrimaryHover: getWithoutThemeValue('static-text-primary-hover'),
    staticTextColorPrimaryInverted: getWithoutThemeValue('static-text-primary-inverted'),
    staticTextColorPrimaryInvertedHover: getWithoutThemeValue('static-text-primary-inverted-hover'),
    staticTextColorPrimaryInvertedPress: getWithoutThemeValue('static-text-primary-inverted-press'),
    staticTextColorPrimaryLight: getWithoutThemeValue('static-text-primary-light'),
    staticTextColorPrimaryPress: getWithoutThemeValue('static-text-primary-press'),
    staticTextColorQuaternary: getWithoutThemeValue('static-text-quaternary'),
    staticTextColorQuaternaryInverted: getWithoutThemeValue('static-text-quaternary-inverted'),
    staticTextColorSecondary: getWithoutThemeValue('static-text-secondary'),
    staticTextColorSecondaryDark: getWithoutThemeValue('static-text-secondary-dark'),
    staticTextColorSecondaryDarkTransparent: getWithoutThemeValue(
        'static-text-secondary-dark-transparent',
    ),
    staticTextColorSecondaryHover: getWithoutThemeValue('static-text-secondary-hover'),
    staticTextColorSecondaryInverted: getWithoutThemeValue('static-text-secondary-inverted'),
    staticTextColorSecondaryInvertedHover: getWithoutThemeValue(
        'static-text-secondary-inverted-hover',
    ),
    staticTextColorSecondaryInvertedPress: getWithoutThemeValue(
        'static-text-secondary-inverted-press',
    ),
    staticTextColorSecondaryLight: getWithoutThemeValue('static-text-secondary-light'),
    staticTextColorSecondaryLightTransparent: getWithoutThemeValue(
        'static-text-secondary-light-transparent',
    ),
    staticTextColorSecondaryPress: getWithoutThemeValue('static-text-secondary-press'),
    staticTextColorTertiary: getWithoutThemeValue('static-text-tertiary'),
    staticTextColorTertiaryDark: getWithoutThemeValue('static-text-tertiary-dark'),
    staticTextColorTertiaryDarkTransparent: getWithoutThemeValue(
        'static-text-tertiary-dark-transparent',
    ),
    staticTextColorTertiaryHover: getWithoutThemeValue('static-text-tertiary-hover'),
    staticTextColorTertiaryInverted: getWithoutThemeValue('static-text-tertiary-inverted'),
    staticTextColorTertiaryInvertedHover: getWithoutThemeValue(
        'static-text-tertiary-inverted-hover',
    ),
    staticTextColorTertiaryInvertedPress: getWithoutThemeValue(
        'static-text-tertiary-inverted-press',
    ),
    staticTextColorTertiaryLight: getWithoutThemeValue('static-text-tertiary-light'),
    staticTextColorTertiaryLightTransparent: getWithoutThemeValue(
        'static-text-tertiary-light-transparent',
    ),
    staticTextColorTertiaryPress: getWithoutThemeValue('static-text-tertiary-press'),
    statusColorAttention: getWithThemeValue('status-attention'),
    statusColorAttentionHover: getWithThemeValue('status-attention-hover'),
    statusColorAttentionInverted: getWithThemeValue('status-attention-inverted'),
    statusColorAttentionInvertedHover: getWithThemeValue('status-attention-inverted-hover'),
    statusColorAttentionInvertedPress: getWithThemeValue('status-attention-inverted-press'),
    statusColorAttentionPress: getWithThemeValue('status-attention-press'),
    statusColorInfo: getWithThemeValue('status-info'),
    statusColorInfoHover: getWithThemeValue('status-info-hover'),
    statusColorInfoInverted: getWithThemeValue('status-info-inverted'),
    statusColorInfoInvertedHover: getWithThemeValue('status-info-inverted-hover'),
    statusColorInfoInvertedPress: getWithThemeValue('status-info-inverted-press'),
    statusColorInfoPress: getWithThemeValue('status-info-press'),
    statusColorNegative: getWithThemeValue('status-negative'),
    statusColorNegativeHover: getWithThemeValue('status-negative-hover'),
    statusColorNegativeInverted: getWithThemeValue('status-negative-inverted'),
    statusColorNegativeInvertedHover: getWithThemeValue('status-negative-inverted-hover'),
    statusColorNegativeInvertedPress: getWithThemeValue('status-negative-inverted-press'),
    statusColorNegativePress: getWithThemeValue('status-negative-press'),
    statusColorPositive: getWithThemeValue('status-positive'),
    statusColorPositiveHover: getWithThemeValue('status-positive-hover'),
    statusColorPositiveInverted: getWithThemeValue('status-positive-inverted'),
    statusColorPositiveInvertedHover: getWithThemeValue('status-positive-inverted-hover'),
    statusColorPositiveInvertedPress: getWithThemeValue('status-positive-inverted-press'),
    statusColorPositivePress: getWithThemeValue('status-positive-press'),
    statusMutedAltColorAttention: getWithThemeValue('status-muted-alt-attention'),
    statusMutedAltColorAttentionHover: getWithThemeValue('status-muted-alt-attention-hover'),
    statusMutedAltColorAttentionInverted: getWithThemeValue('status-muted-alt-attention-inverted'),
    statusMutedAltColorAttentionInvertedHover: getWithThemeValue(
        'status-muted-alt-attention-inverted-hover',
    ),
    statusMutedAltColorAttentionInvertedPress: getWithThemeValue(
        'status-muted-alt-attention-inverted-press',
    ),
    statusMutedAltColorAttentionPress: getWithThemeValue('status-muted-alt-attention-press'),
    statusMutedAltColorInfo: getWithThemeValue('status-muted-alt-info'),
    statusMutedAltColorInfoHover: getWithThemeValue('status-muted-alt-info-hover'),
    statusMutedAltColorInfoInverted: getWithThemeValue('status-muted-alt-info-inverted'),
    statusMutedAltColorInfoInvertedHover: getWithThemeValue('status-muted-alt-info-inverted-hover'),
    statusMutedAltColorInfoInvertedPress: getWithThemeValue('status-muted-alt-info-inverted-press'),
    statusMutedAltColorInfoPress: getWithThemeValue('status-muted-alt-info-press'),
    statusMutedAltColorNegative: getWithThemeValue('status-muted-alt-negative'),
    statusMutedAltColorNegativeHover: getWithThemeValue('status-muted-alt-negative-hover'),
    statusMutedAltColorNegativeInverted: getWithThemeValue('status-muted-alt-negative-inverted'),
    statusMutedAltColorNegativeInvertedHover: getWithThemeValue(
        'status-muted-alt-negative-inverted-hover',
    ),
    statusMutedAltColorNegativeInvertedPress: getWithThemeValue(
        'status-muted-alt-negative-inverted-press',
    ),
    statusMutedAltColorNegativePress: getWithThemeValue('status-muted-alt-negative-press'),
    statusMutedAltColorPositive: getWithThemeValue('status-muted-alt-positive'),
    statusMutedAltColorPositiveHover: getWithThemeValue('status-muted-alt-positive-hover'),
    statusMutedAltColorPositiveInverted: getWithThemeValue('status-muted-alt-positive-inverted'),
    statusMutedAltColorPositiveInvertedHover: getWithThemeValue(
        'status-muted-alt-positive-inverted-hover',
    ),
    statusMutedAltColorPositiveInvertedPress: getWithThemeValue(
        'status-muted-alt-positive-inverted-press',
    ),
    statusMutedAltColorPositivePress: getWithThemeValue('status-muted-alt-positive-press'),
    statusMutedColorAttention: getWithThemeValue('status-muted-attention'),
    statusMutedColorAttentionHover: getWithThemeValue('status-muted-attention-hover'),
    statusMutedColorAttentionInverted: getWithThemeValue('status-muted-attention-inverted'),
    statusMutedColorAttentionInvertedHover: getWithThemeValue(
        'status-muted-attention-inverted-hover',
    ),
    statusMutedColorAttentionInvertedPress: getWithThemeValue(
        'status-muted-attention-inverted-press',
    ),
    statusMutedColorAttentionPress: getWithThemeValue('status-muted-attention-press'),
    statusMutedColorInfo: getWithThemeValue('status-muted-info'),
    statusMutedColorInfoHover: getWithThemeValue('status-muted-info-hover'),
    statusMutedColorInfoInverted: getWithThemeValue('status-muted-info-inverted'),
    statusMutedColorInfoInvertedHover: getWithThemeValue('status-muted-info-inverted-hover'),
    statusMutedColorInfoInvertedPress: getWithThemeValue('status-muted-info-inverted-press'),
    statusMutedColorInfoPress: getWithThemeValue('status-muted-info-press'),
    statusMutedColorNegative: getWithThemeValue('status-muted-negative'),
    statusMutedColorNegativeHover: getWithThemeValue('status-muted-negative-hover'),
    statusMutedColorNegativeInverted: getWithThemeValue('status-muted-negative-inverted'),
    statusMutedColorNegativeInvertedHover: getWithThemeValue(
        'status-muted-negative-inverted-hover',
    ),
    statusMutedColorNegativeInvertedPress: getWithThemeValue(
        'status-muted-negative-inverted-press',
    ),
    statusMutedColorNegativePress: getWithThemeValue('status-muted-negative-press'),
    statusMutedColorPositive: getWithThemeValue('status-muted-positive'),
    statusMutedColorPositiveHover: getWithThemeValue('status-muted-positive-hover'),
    statusMutedColorPositiveInverted: getWithThemeValue('status-muted-positive-inverted'),
    statusMutedColorPositiveInvertedHover: getWithThemeValue(
        'status-muted-positive-inverted-hover',
    ),
    statusMutedColorPositiveInvertedPress: getWithThemeValue(
        'status-muted-positive-inverted-press',
    ),
    statusMutedColorPositivePress: getWithThemeValue('status-muted-positive-press'),
    textColorAccent: getWithThemeValue('text-accent'),
    textColorAttention: getWithThemeValue('text-attention'),
    textColorAttentionHover: getWithThemeValue('text-attention-hover'),
    textColorAttentionInverted: getWithThemeValue('text-attention-inverted'),
    textColorAttentionInvertedHover: getWithThemeValue('text-attention-inverted-hover'),
    textColorAttentionInvertedPress: getWithThemeValue('text-attention-inverted-press'),
    textColorAttentionPress: getWithThemeValue('text-attention-press'),
    textColorDisabled: getWithThemeValue('text-disabled'),
    textColorDisabledInverted: getWithThemeValue('text-disabled-inverted'),
    textColorDisabledTransparent: getWithThemeValue('text-disabled-transparent'),
    textColorInfo: getWithThemeValue('text-info'),
    textColorInfoHover: getWithThemeValue('text-info-hover'),
    textColorInfoInverted: getWithThemeValue('text-info-inverted'),
    textColorInfoInvertedHover: getWithThemeValue('text-info-inverted-hover'),
    textColorInfoInvertedPress: getWithThemeValue('text-info-inverted-press'),
    textColorInfoPress: getWithThemeValue('text-info-press'),
    textColorLink: getWithThemeValue('text-link'),
    textColorNegative: getWithThemeValue('text-negative'),
    textColorNegativeHover: getWithThemeValue('text-negative-hover'),
    textColorNegativeInverted: getWithThemeValue('text-negative-inverted'),
    textColorNegativeInvertedHover: getWithThemeValue('text-negative-inverted-hover'),
    textColorNegativeInvertedPress: getWithThemeValue('text-negative-inverted-press'),
    textColorNegativePress: getWithThemeValue('text-negative-press'),
    textColorPositive: getWithThemeValue('text-positive'),
    textColorPositiveHover: getWithThemeValue('text-positive-hover'),
    textColorPositiveInverted: getWithThemeValue('text-positive-inverted'),
    textColorPositiveInvertedHover: getWithThemeValue('text-positive-inverted-hover'),
    textColorPositiveInvertedPress: getWithThemeValue('text-positive-inverted-press'),
    textColorPositivePress: getWithThemeValue('text-positive-press'),
    textColorPrimary: getWithThemeValue('text-primary'),
    textColorPrimaryHover: getWithThemeValue('text-primary-hover'),
    textColorPrimaryInverted: getWithThemeValue('text-primary-inverted'),
    textColorPrimaryInvertedHover: getWithThemeValue('text-primary-inverted-hover'),
    textColorPrimaryInvertedPress: getWithThemeValue('text-primary-inverted-press'),
    textColorPrimaryPress: getWithThemeValue('text-primary-press'),
    textColorQuaternary: getWithThemeValue('text-quaternary'),
    textColorQuaternaryInverted: getWithThemeValue('text-quaternary-inverted'),
    textColorSecondary: getWithThemeValue('text-secondary'),
    textColorSecondaryHover: getWithThemeValue('text-secondary-hover'),
    textColorSecondaryInverted: getWithThemeValue('text-secondary-inverted'),
    textColorSecondaryInvertedHover: getWithThemeValue('text-secondary-inverted-hover'),
    textColorSecondaryInvertedPress: getWithThemeValue('text-secondary-inverted-press'),
    textColorSecondaryInvertedTransparent: getWithThemeValue('text-secondary-inverted-transparent'),
    textColorSecondaryPress: getWithThemeValue('text-secondary-press'),
    textColorSecondaryTransparent: getWithThemeValue('text-secondary-transparent'),
    textColorTertiary: getWithThemeValue('text-tertiary'),
    textColorTertiaryHover: getWithThemeValue('text-tertiary-hover'),
    textColorTertiaryInverted: getWithThemeValue('text-tertiary-inverted'),
    textColorTertiaryInvertedHover: getWithThemeValue('text-tertiary-inverted-hover'),
    textColorTertiaryInvertedPress: getWithThemeValue('text-tertiary-inverted-press'),
    textColorTertiaryInvertedTransparent: getWithThemeValue('text-tertiary-inverted-transparent'),
    textColorTertiaryPress: getWithThemeValue('text-tertiary-press'),
    textColorTertiaryTransparent: getWithThemeValue('text-tertiary-transparent'),
    transparent: getWithoutThemeValue('dynamic-nulled'),
    transparentColorDefault: getWithThemeValue('transparent-default'),
    transparentColorDefaultHover: getWithThemeValue('transparent-default-hover'),
    transparentColorDefaultInvertedHover: getWithThemeValue('transparent-default-inverted-hover'),
    transparentColorDefaultInvertedPress: getWithThemeValue('transparent-default-inverted-press'),
    transparentColorDefaultPress: getWithThemeValue('transparent-default-press'),
};
