name: setup-git-user

description: Setup git user

inputs:
    name:
        description: The user name
        required: true
        type: string
    email:
        description: The user email
        required: true
        type: string

runs:
    using: composite
    steps:
        - name: setup git user
          shell: bash
          run: |
              git config user.name "${{ inputs.name }}"
              git config user.email "${{ inputs.email }}"
