type TConfig = Record<string, string[]>;

export const CONFIG: TConfig = {
    Кнопки: ['Button', 'CustomButton', 'PickerButton', 'IconButton', 'ActionButton', 'Link'],
    'Ввод данных': [
        'Input',
        'AmountInput',
        'NumberInput',
        'PasswordInput',
        'PhoneInput',
        'IntlPhoneInput',
        'MaskedInput',
        'CodeInput',
        'SliderInput',
        'Textarea',
        'Select',
        'InputAutocomplete',
        'Checkbox',
        'CheckboxGroup',
        'Radio',
        'RadioGroup',
        'Switch',
        'Slider',
        'Tag',
        'FilterTag',
    ],
    'Ввод даты и времени': [
        'CalendarInput',
        'DateInput',
        'DateRangeInput',
        'DateTimeInput',
        'TimeInput',
        'Calendar',
        'CalendarRange',
    ],
    'Загрузка файлов': ['Dropzone', 'FileUploadItem', 'Attach'],
    'Модальные сущности': ['Modal', 'SidePanel', 'BottomSheet', 'Popover', 'Tooltip'],
    'Индикаторы прогресса': [
        'ProgressBar',
        'SteppedProgressBar',
        'HatchingProgressBar',
        'Spinner',
        'Skeleton',
    ],
    Уведомления: ['Notification', 'Toast', 'SystemMessage', 'Plate'],
    Аутентификация: ['PassCode', 'PatternLock', 'Confirmation'],
    Ячейки: ['GenericWrapper', 'PureCell'],
    Навигация: ['Tabs', 'Pagination'],
    Индикаторы: ['Badge', 'Status'],
    Текст: ['Typography', 'List'],
    'Отображение данных': [
        'Amount',
        'IconView',
        'CardImage',
        'Table',
        'Chart',
        'Gallery',
        'Comment',
        'Collapse',
    ],
    Лейаут: ['Space', 'Gap', 'Grid'],
};
