name: resolve demo params

inputs:
    version:
        description: Version of @balafla/core-components package, tag or commit sha
        required: false
    dir:
        description: Demo directory
        required: false

outputs:
    ref:
        description: Checkout ref
        value: ${{ steps.resolve-ref.outputs.result }}
    dir:
        description: Demo directory
        value: ${{ steps.resolve-dir.outputs.result }}

runs:
    using: composite
    steps:
        - name: install dependencies
          shell: bash
          working-directory: tools/gh-actions/resolve-demo-params
          run: |
              yarn install --frozen-lockfile

        - id: resolve-ref
          uses: actions/github-script@v7
          with:
              result-encoding: string
              script: |
                  const run = require('./tools/gh-actions/resolve-demo-params/resolve-ref.js');
                  const inputs = ${{ toJSON(inputs) }};

                  return await run({ github, context, core, glob, io, exec, inputs });

        - uses: actions/checkout@v4
          if: ${{ inputs.version != '' }}
          with:
              ref: ${{ steps.resolve-ref.outputs.result }}
              fetch-tags: true
              path: checkout-ref

        - id: resolve-dir
          uses: actions/github-script@v7
          with:
              result-encoding: string
              script: |
                  const run = require('./tools/gh-actions/resolve-demo-params/resolve-dir.js');
                  const inputs = ${{ toJSON(inputs) }};

                  return await run({ github, context, core, glob, io, exec, inputs });
