name: Tests & Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
    test:
        name: run tests

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn

            - name: Run lint
              run: yarn lint

            - name: Setup timezone
              uses: zcong1993/setup-timezone@master
              with:
                timezone: Europe/Moscow

            - name: Run test
              run: yarn test --coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

    build:
        name: build packages

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn

            - name: Run build
              run: yarn build
              env:
                BUILD_CONCURRENCY: 5
