name: changesets

on: pull_request

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

env:
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

jobs:
    changesets:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup CI
              uses: ./.github/actions/ci-setup

            - name: Apply changesets
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn version-packages
