name: changesets

on: pull_request

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    check:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Checkout
              uses: core-ds/core-components/.github/actions/ci-setup@master

            - name: Apply changesets
              shell: bash
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn version-packages
