name: demo

on:
    workflow_call:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag, ref or sha
                required: false
                type: string
                default: ${{ github.ref }}
            directory:
                description: Directory deploy to
                required: false
                type: string
            deploy-repository:
                description: Repository
                required: false
                type: string
                default: ${{ github.repository }}
        outputs:
            run-id:
                description: Artifact workflow run id
                value: ${{ case(jobs.variants.outputs.empty == 'true', jobs.build-demo.outputs.run-id, jobs.build-variants-demo.outputs.run-id) }}
    workflow_dispatch:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag or sha
                required: false
                type: string
            directory:
                description: Directory deploy to
                required: false
                type: string

concurrency:
    group: demo-${{ case(inputs.version == '', github.ref, inputs.version) }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    params:
        uses: ./.github/workflows/resolve-demo-params.yml
        secrets: inherit
        with:
            version: ${{ inputs.version }}
            directory: ${{ inputs.directory }}

    sha:
        needs: params
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.find.outputs.result }}
        steps:
            - uses: actions/checkout@v6
              if: ${{ github.event_name == 'workflow_dispatch' }}
              with:
                  ref: ${{ needs.params.outputs.ref }}

            - id: find
              if: ${{ github.event_name == 'workflow_dispatch' }}
              uses: actions/github-script@v8
              with:
                  result-encoding: string
                  script: |
                      const { stdout } = await exec.getExecOutput('git', ['rev-list', '-n', '1', 'HEAD']);
                      return stdout.trim();

    variants:
        uses: ./.github/workflows/variants.yml

    build-variants-demo:
        if: ${{ needs.variants.outputs.empty == 'false' }}
        needs: [params, variants]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.json) }}
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            ref: ${{ needs.params.outputs.ref }}
            variant: ${{ matrix.variant }}
            artifact-name: ${{ matrix.variant }}

    deploy-variants:
        needs: [build-variants-demo, params, sha, variants]
        strategy:
            max-parallel: 1
            matrix:
                include: ${{ fromJson(needs.variants.outputs.json) }}
        uses: ./.github/workflows/deploy-demo.yml
        secrets: inherit
        with:
            run-id: ${{ needs.build-variants-demo.outputs.run-id }}
            directory: '${{ needs.params.outputs.directory }}-${{ matrix.variant }}'
            variant: ${{ matrix.variant }}
            artifact-name: ${{ matrix.variant }}
            deploy-repository: ${{ inputs.deploy-repository }}
            sha: ${{ needs.sha.outputs.result }}

    build-demo:
        if: ${{ needs.variants.outputs.empty == 'true' }}
        needs: [params, variants]
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            ref: ${{ needs.params.outputs.ref }}

    deploy:
        needs: [build-demo, sha, params]
        uses: ./.github/workflows/deploy-demo.yml
        secrets: inherit
        with:
            run-id: ${{ needs.build-demo.outputs.run-id }}
            directory: ${{ needs.params.outputs.directory }}
            deploy-repository: ${{ inputs.deploy-repository }}
            sha: ${{ needs.sha.outputs.result }}
