name: demo

on:
    workflow_call:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag, ref or sha
                required: false
                type: string
                default: ${{ github.ref }}
            directory:
                description: Directory deploy to
                required: false
                type: string
        outputs:
            run-id:
                description: Artifact workflow run id
                value: ${{ case( jobs.variants.outputs.result == '', jobs.build-demo.outputs.run-id, jobs.build-variants-demo.outputs.run-id ) }}
    workflow_dispatch:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag or sha
                required: false
                type: string
            directory:
                description: Directory deploy to
                required: false
                type: string

concurrency:
    group: ${{ case(github.event_name == 'workflow_dispatch', github.workflow, 'demo') }}-${{ case(inputs.version == '', github.ref, inputs.version) }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    params:
        uses: ./.github/workflows/resolve-demo-params.yml
        secrets: inherit
        with:
            version: ${{ inputs.version }}
            directory: ${{ inputs.directory }}

    variants:
        uses: ./.github/workflows/variants.yml

    build-variants-demo:
        if: ${{ needs.variants.outputs.result != '' }}
        needs: [params, variants]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.result) }}
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            ref: ${{ needs.params.outputs.ref }}
            variant: ${{ matrix.variant }}
            artifact-name: ${{ matrix.variant }}

    deploy-variants:
        needs: [build-variants-demo, params, variants]
        strategy:
            max-parallel: 1
            matrix:
                include: ${{ fromJson(needs.variants.outputs.result) }}
        uses: ./.github/workflows/deploy-demo.yml
        secrets: inherit
        with:
            run-id: ${{ needs.build-variants-demo.outputs.run-id }}
            directory: '${{ needs.params.outputs.directory }}-${{ matrix.variant }}'
            variant: ${{ matrix.variant }}
            artifact-name: ${{ matrix.variant }}

    build-demo:
        if: ${{ needs.variants.outputs.result == '' }}
        needs: [params, variants]
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            ref: ${{ needs.params.outputs.ref }}

    deploy:
        needs: [build-demo, params]
        uses: ./.github/workflows/deploy-demo.yml
        secrets: inherit
        with:
            run-id: ${{ needs.build-demo.outputs.run-id }}
            directory: ${{ needs.params.outputs.directory }}
