name: demo

on:
    workflow_dispatch:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag or sha
                required: false
                type: string
            directory:
                description: Directory deploy to
                required: false
                type: string

concurrency:
    group: demo-${{ case(inputs.version == '', github.ref, inputs.version) }}
    cancel-in-progress: true

jobs:
    demo:
        uses: core-ds/core-components/.github/workflows/demo.yml@master
        with:
            version: ${{ inputs.version }}
            directory: ${{ inputs.directory }}
