name: deploy-demo

on:
    workflow_call:
        inputs:
            run-id:
                description: Artifact workflow run id
                required: true
                type: string
            directory:
                description: Deploy directory
                required: true
                type: string
            variant:
                description: Variant of core components
                required: false
                type: string
                default: default
            artifact-name:
                description: Artifact name
                required: false
                type: string
                default: build
            repository:
                description: Repository
                required: false
                type: string
                default: ${{ github.repository }}

defaults:
    run:
        shell: bash

jobs:
    repository:
        runs-on: ubuntu-latest
        outputs:
            owner: ${{ steps.repository.outputs.owner }}
            repo: ${{ steps.repository.outputs.repo }}
            full-name: ${{ steps.repository.outputs.result }}
        steps:
            - id: repository
              uses: actions/github-script@v8
              with:
                  result-encoding: string
                  script: |
                      const repository = '${{ inputs.repository }}';
                      const [owner, repo] = repository.split('/');

                      core.setOutput('owner', owner);
                      core.setOutput('repo', repo);

                      return repository;

    deploy:
        name: deploy
        needs: repository
        runs-on: ubuntu-latest
        outputs:
            url: 'https://${{ needs.repository.outputs.owner }}.github.io/${{ needs.repository.outputs.repo }}/${{ inputs.directory }}'
        steps:
            - name: generate app token
              id: generate-token
              uses: actions/create-github-app-token@v2
              with:
                  app-id: ${{ vars.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}
                  owner: ${{ needs.repository.outputs.owner }}
                  repositories: ${{ needs.repository.outputs.repo }}

            - uses: actions/checkout@v6
              with:
                  repository: ${{ needs.repository.outputs.full-name }}
                  token: ${{ steps.generate-token.outputs.token }}
                  ref: gh-pages
                  lfs: true

            - name: clean up
              run: |
                  rm -rf '${{ inputs.directory }}'

            - name: download build
              uses: actions/download-artifact@v8
              with:
                  name: '${{ inputs.artifact-name }}'
                  path: '${{ inputs.directory }}'
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ inputs.run-id }}

            - name: copy legacy archive-versions.json
              if: ${{ startsWith(inputs.directory, 'master') }}
              run: |
                  cp archive-versions.json '${{ inputs.directory }}'

            - name: deploy
              uses: core-ds/core-components/.github/actions/commit-and-push@master
              with:
                  message: 'Deploy to GitHub Pages'

    pull-request:
        needs: repository
        name: find pull request
        runs-on: ubuntu-latest
        outputs:
            number: ${{ steps.pull-request.outputs.result }}
        steps:
            - name: find open pull request
              id: pull-request
              uses: actions/github-script@v8
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  result-encoding: string
                  script: |
                      const { data } = await octokit.rest.repos.listPullRequestsAssociatedWithCommit({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          commit_sha: context.sha,
                      });
                      const pr = data.find((p) => `refs/heads/${p.head.ref}` === context.ref) ?? data[0];

                      return pr?.number ?? '';

    comment:
        name: comment
        runs-on: ubuntu-latest
        needs: [deploy, pull-request, repository]
        if: ${{ needs.pull-request.outputs.number != '' }}
        steps:
            - name: find comment
              uses: peter-evans/find-comment@v4
              id: comment
              with:
                  repository: ${{ needs.repository.outputs.full-name }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  issue-number: ${{ needs.pull-request.outputs.number }}
                  comment-author: 'github-actions[bot]'
                  body-includes: Demo build (${{ inputs.variant }})

            - name: create or update comment
              uses: peter-evans/create-or-update-comment@v5
              with:
                  repository: ${{ needs.repository.outputs.full-name }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  comment-id: ${{ steps.comment.outputs.comment-id }}
                  issue-number: ${{ needs.pull-request.outputs.number }}
                  body: |
                      ## Demo build (${{ inputs.variant }})

                      [${{ needs.deploy.outputs.url }}](${{ needs.deploy.outputs.url }})
                  reactions: rocket
                  edit-mode: replace
