name: main

on:
    pull_request:
        branches-ignore:
            - next
    push:
        branches:
            - master
            - next
            - 'version/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    variants:
        uses: ./.github/workflows/variants.yml

    build:
        needs: [variants, setup-variant]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.config) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup variant
              uses: ./.github/actions/setup-variant
              with:
                  variant: ${{ matrix.variant }}

            - name: Setup CI
              uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - name: Build
              run: yarn build
              env:
                  BUILD_CONCURRENCY: 4

    lint:
        needs: [variants, setup-variant]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.config) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup variant
              uses: ./.github/actions/setup-variant
              with:
                  variant: ${{ matrix.variant }}

            - name: Setup CI
              uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - name: Check package.json
              run: |
                  yarn check-package-json

            - name: Check tsconfig
              run: |
                  yarn tsconfig check

            - name: Format
              run: |
                  yarn format

            - name: Lint
              run: |
                  yarn lint

    test:
        needs: [variants, setup-variant]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.config) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup variant
              uses: ./.github/actions/setup-variant
              with:
                  variant: ${{ matrix.variant }}

            - name: Setup CI
              uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - name: Setup timezone
              run: |
                  sudo timedatectl set-timezone 'Europe/Moscow'

            - name: Build themes
              run: |
                  yarn build --include @alfalab/core-components-themes

            - name: Run tests
              run: |
                  yarn test --coverage

            - name: Upload coverage
              if: ${{ matrix.variant == 'default' }}
              uses: actions/upload-artifact@v7
              with:
                  name: coverage
                  path: '${{ github.workspace }}/coverage'

    codemod-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup CI
              uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - name: Run codemod test
              run: |
                  yarn test:codemod

    upload-coverage:
        needs: test
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'core-ds/core-components' }}
        steps:
            - name: Download coverage
              uses: actions/download-artifact@v8
              with:
                  name: coverage
                  path: '${{ github.workspace }}/coverage'

            - name: Upload coverage to coveralls
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    demo:
        uses: ./.github/workflows/demo.yml
        secrets: inherit
        with:
            version: ${{ case(github.event_name == 'pull_request', github.event.pull_request.head.sha, github.ref) }}
            directory: ${{ github.event.pull_request.number }}

    screenshot-test:
        needs: demo
        strategy:
            fail-fast: false
            matrix:
                variant:
                    - default
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  lfs: true

            - name: Setup CI
              uses: ./.github/actions/ci-setup

            - name: Download demo
              uses: actions/download-artifact@v8
              with:
                  name: ${{ matrix.variant }}
                  path: build
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ needs.demo.outputs.run-id }}

              # https://github.com/americanexpress/jest-image-snapshot/issues/281
            - name: Run screenshot test
              uses: actions/github-script@v8
              with:
                  script: |
                      const { stderr } = await exec.getExecOutput('yarn', ['test:screenshots']);

                      if (/[0-9]+ snapshots? written from [0-9]+ test suites?/.test(stderr)) {
                          core.setFailed(`Please add missing ${{ matrix.variant }} screenshots`);
                      }

            - name: Upload diff
              uses: actions/upload-artifact@v7
              if: failure()
              with:
                  name: 'diff-${{ matrix.variant }}'
                  path: packages/**/__diff_output__/*
                  if-no-files-found: ignore

    setup-variant:
        needs: variants
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.config) }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup variant
              uses: ./.github/actions/setup-variant
              with:
                  variant: ${{ matrix.variant }}

    upload-pull-request-data:
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            - name: Write pull request data to json
              run: |
                  mkdir -p pull-request

                  {
                      echo '${{ toJson(github.event.pull_request) }}'
                  } > pull-request/data.json

            - name: Upload pull request data
              uses: actions/upload-artifact@v7
              with:
                  name: pull-request
                  path: pull-request

    search-vars:
        needs: variants
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.config) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup variant
              uses: ./.github/actions/setup-variant
              with:
                  variant: ${{ matrix.variant }}

            - name: Setup CI
              uses: ./.github/actions/ci-setup

            - name: Run build
              env:
                  BUILD_WITHOUT_CSS_VARS: true
                  BUILD_CONCURRENCY: 4
                  BUILD_MODERN_ONLY: true
              run: |
                  yarn build

            - name: Search
              run: yarn non-existent-css-vars

    ok:
        runs-on: ubuntu-latest
        if: always()
        needs: [lint, build, demo, test, screenshot-test, setup-variant, codemod-test, search-vars]
        env:
            FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
        steps:
            - name: Check for failure
              run: |
                  echo $FAILURE
                  if [ "$FAILURE" = "false" ]; then
                    exit 0
                  else
                    exit 1
                  fi
