name: Main

on:
    pull_request:
    push:
        branches:
            - master
            - beta
            - next

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/ci-setup

            - name: Run build
              run: yarn build
              env:
                  BUILD_CONCURRENCY: 5

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/ci-setup

            - name: Check tsconfig
              run: |
                  yarn tsconfig check

            - name: Run lint
              run: |
                  yarn lint

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/ci-setup

            - name: Setup timezone
              uses: zcong1993/setup-timezone@master
              with:
                  timezone: Europe/Moscow

            - name: Run test
              run: |
                  yarn test --coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    ci-ok:
        name: CI OK
        runs-on: ubuntu-latest
        if: always()
        needs: [lint, build, test]
        env:
            FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
        steps:
            - name: Check for failure
              run: |
                  echo $FAILURE
                  if [ "$FAILURE" = "false" ]; then
                    exit 0
                  else
                    exit 1
                  fi
