name: main

on:
    pull_request:
        branches-ignore:
            - next
    push:
        branches:
            - master
            - next

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    variants:
        uses: ./.github/workflows/variants.yml

    build:
        needs: [variants, patch]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.json) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ matrix.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

            - uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - name: run build
              run: yarn build
              env:
                  BUILD_CONCURRENCY: 4

    lint:
        needs: [variants, patch]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.json) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ matrix.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

            - uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - name: check package.json
              run: |
                  yarn check-package-json

            - name: check tsconfig
              run: |
                  yarn tsconfig check

            - name: run format
              run: |
                  yarn format

            - name: run lint
              run: |
                  yarn lint

    test:
        needs: [variants, patch]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.json) }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ matrix.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

            - uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - name: setup timezone
              run: |
                  sudo timedatectl set-timezone 'Europe/Moscow'

            - name: build themes
              run: |
                  yarn build --include @alfalab/core-components-themes

            - name: run test
              run: |
                  yarn test --coverage

            - if: ${{ matrix.variant == 'default' }}
              uses: actions/upload-artifact@v7
              with:
                  name: coverage
                  path: '${{ github.workspace }}/coverage'

    codemod-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - name: run codemod test
              run: |
                  yarn test:codemod

    upload-coverage:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v8
              with:
                  name: coverage
                  path: '${{ github.workspace }}/coverage'

            - uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    demo:
        uses: ./.github/workflows/demo.yml
        secrets: inherit
        with:
            directory: ${{ case(github.event_name == 'pull_request', github.event.pull_request.number, github.ref_name) }}
            deploy-repository: ${{ github.event.pull_request.head.repo.full_name }}

    screenshot-test:
        needs: demo
        strategy:
            fail-fast: false
            matrix:
                variant:
                    - default
        env:
            CORE_COMPONENTS_VARIANT: ${{ matrix.variant }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  lfs: true

            - uses: ./.github/actions/ci-setup

            - name: download build
              uses: actions/download-artifact@v8
              with:
                  name: ${{ matrix.variant }}
                  path: build
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ needs.demo.outputs.run-id }}

              # https://github.com/americanexpress/jest-image-snapshot/issues/281
            - name: run screenshot test
              uses: actions/github-script@v8
              with:
                  script: |
                      const { stderr } = await exec.getExecOutput('yarn', ['test:screenshots']);

                      if (/[0-9]+ snapshots? written from [0-9]+ test suites?/.test(stderr)) {
                          core.setFailed(`Please add missing ${{ matrix.variant }} screenshots`);
                      }

            - uses: actions/upload-artifact@v7
              if: failure()
              with:
                  name: 'diff-${{ matrix.variant }}'
                  path: packages/**/__diff_output__/*
                  if-no-files-found: ignore

    patch:
        needs: [variants]
        strategy:
            matrix:
                include: ${{ fromJson(needs.variants.outputs.json) }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ matrix.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

    ci-ok:
        name: ci ok
        runs-on: ubuntu-latest
        if: always()
        needs: [lint, build, demo, test, screenshot-test, patch, codemod-test]
        env:
            FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
        steps:
            - name: check for failure
              run: |
                  echo $FAILURE
                  if [ "$FAILURE" = "false" ]; then
                    exit 0
                  else
                    exit 1
                  fi
