name: Beta release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Бета версия в виде x.x.x-beta.x'
        required: true
        default: ''
        type: string

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check permissions
        if: ${{ contains(fromJSON('["dHIM24","SiebenSieben","hextion","fulcanellee"]'), github.actor) == false }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("You don't have permission to run this workflow!");

      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn --pure-lockfile

      - name: Build app
        run: yarn build
        env:
          BUILD_CONCURRENCY: 5

      - name: Set NPM Token
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npm run pub:beta-ci
        env:
          VERSION: ${{ github.event.inputs.version }}
