name: beta-release

on: workflow_dispatch

jobs:
    stub:
        runs-on: ubuntu-latest
        steps:
            - name: Print help and exit
              shell: bash
              run: |
                  echo "This workflow does nothing. Make sure ref is correct."
                  echo 'Use this workflow for core-components version 49.'
                  echo 'Use `release` workflow for core-components version 49 and higher.'
                  exit 1
