name: remove-demo

on:
    pull_request:
        types: [closed]
    workflow_call:
        inputs:
            directory:
                description: Directory or list of directories separated by comma
                required: true
                type: string
    workflow_dispatch:
        inputs:
            directory:
                description: Directory or list of directories separated by comma
                required: true
                type: string
            include-variants:
                description: Include variant name into demo directory name
                required: false
                type: boolean
                default: false

concurrency:
    group: remove-demo-${{ case(github.event_name == 'pull_request', github.event.pull_request.number, inputs.directory) }}
    cancel-in-progress: false

defaults:
    run:
        shell: bash

jobs:
    variants:
        if: ${{ inputs.include-variants || github.event_name == 'pull_request' }}
        uses: ./.github/workflows/variants.yml
        secrets: inherit

    resolve-directory:
        name: resolve directory
        needs: variants
        if: ${{ always() && (needs.variants.result == 'success' || needs.variants.result == 'skipped') }}
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.resolve.outputs.result }}
        steps:
            - id: resolve
              uses: actions/github-script@v8
              with:
                  script: |
                      const directories =
                          '${{ case(github.event_name == 'pull_request', github.event.pull_request.number, inputs.directory) }}'
                              .split(/\s*,\s*/)
                              .filter(Boolean)
                              .map(directory => ({ directory }));

                      if (directories.length === 0) {
                          core.warning("Empty directories list");
                      }

                      if ('${{ needs.variants.result }}' === 'skipped' || '${{ needs.variants.outputs.empty }}' === 'true') {
                          return directories;
                      }

                      const variants = JSON.parse('${{ needs.variants.outputs.json }}');

                      return directories.flatMap(({ directory }) => [{ directory }, ...variants.map(({ variant }) => ({ directory: `${directory}-${variant}` }))]);

    remove-demo:
        name: remove demo
        needs: [resolve-directory]
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'core-ds/core-components' && always() && needs.resolve-directory.result == 'success' }}
        steps:
            - uses: actions/checkout@v6
              with:
                  ref: gh-pages
                  lfs: true
                  token: ${{ secrets.GITHUB_TOKEN }}

            - id: remove
              uses: actions/github-script@v8
              with:
                  result-encoding: string
                  script: |
                      const directories = JSON.parse('${{ needs.resolve-directory.outputs.result }}');

                      await Promise.all(directories.map(({ directory }) => exec.exec('rm', ['-rf', directory])));

                      const { stdout } = await exec.getExecOutput('git', ['status', '--porcelain']);

                      return stdout.split('\n').some((line) => /^\s+D\s+.*$/.test(line));

            - name: deploy
              if: ${{ steps.remove.outputs.result == 'true' }}
              uses: ./.github/actions/commit-and-push
              with:
                  message: 'Deploy to GitHub Pages'
