name: remove-demo

on:
    pull_request:
        types: [closed]
    workflow_dispatch:
        inputs:
            directory:
                description: Directory or list of directories separated by comma
                required: true
                type: string

concurrency:
    group: remove-demo-${{ case(github.event_name == 'pull_request', github.event.pull_request.number, inputs.directory) }}
    cancel-in-progress: true

jobs:
    remove-demo:
        uses: core-ds/core-components/.github/workflows/remove-demo.yml@master
        with:
            directory: ${{ case(github.event_name == 'pull_request', github.event.pull_request.number, inputs.directory) }}
