name: resolve-demo-params

on:
    workflow_call:
        inputs:
            version:
                description: Version of @alfalab/core-components package, tag or SHA
                required: false
                type: string
                default: ${{ github.ref }}
            directory:
                description: Demo directory
                required: false
                type: string
        outputs:
            ref:
                description: Checkout ref
                value: ${{ jobs.resolve.outputs.ref }}
            directory:
                description: Demo directory
                value: ${{ jobs.resolve.outputs.directory }}

defaults:
    run:
        shell: bash

jobs:
    resolve:
        runs-on: ubuntu-latest
        outputs:
            ref: ${{ steps.resolve-ref.outputs.result }}
            directory: ${{ steps.resolve-directory.outputs.result }}
        env:
            # passing input via env as a workaround https://github.com/actions/toolkit/issues/1124
            CORE_COMPONENTS_DEMO_VERSION: ${{ inputs.version }}
            CORE_COMPONENTS_DEMO_DIRECTORY: ${{ inputs.directory }}
        steps:
            - uses: actions/checkout@v6

            - uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - id: resolve-ref
              uses: actions/github-script@v8
              with:
                  result-encoding: string
                  script: |
                      const resolveRef = require('@alfalab/core-components-demo-params/resolve-ref');

                      return await resolveRef({
                          require,
                          __original_require__,
                          github,
                          octokit,
                          context,
                          core,
                          exec,
                          glob,
                          io,
                      });

            - uses: actions/checkout@v6
              if: ${{ steps.resolve-ref.outputs.result != github.ref }}
              with:
                  ref: ${{ steps.resolve-ref.outputs.result }}
                  fetch-tags: true
                  path: checkout-ref

            - id: resolve-directory
              uses: actions/github-script@v8
              with:
                  result-encoding: string
                  script: |
                      const resolveDirectory = require('@alfalab/core-components-demo-params/resolve-directory');

                      return await resolveDirectory({
                          require,
                          __original_require__,
                          github,
                          octokit,
                          context,
                          core,
                          exec,
                          glob,
                          io,
                      });
