name: resolve-variant-demo-directory

on:
    workflow_call:
        inputs:
            variant:
                description: Variant of core components
                required: false
                type: string
                default: default
            directory:
                description: Demo directory
                required: false
                type: string
        outputs:
            directory:
                description: Resolved demo directory
                value: ${{ jobs.resolve.outputs.directory }}

defaults:
    run:
        shell: bash

jobs:
    resolve:
        runs-on: ubuntu-latest
        outputs:
            directory: ${{ steps.resolve.outputs.result }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ inputs.variant }}
            CORE_COMPONENTS_DEMO_DIRECTORY: ${{ inputs.directory }}
        steps:
            - uses: actions/checkout@v5

            - uses: ./.github/actions/ci-setup

            - id: resolve
              uses: actions/github-script@v8
              with:
                  result-encoding: string
                  script: |
                      const resolveVariantDirectory = require('@alfalab/core-components-demo-params/resolve-variant-directory');

                      return await resolveVariantDirectory({
                          require,
                          __original_require__,
                          github,
                          octokit,
                          context,
                          core,
                          exec,
                          glob,
                          io,
                      });
