name: snapshot-release

on:
    workflow_call:
    workflow_dispatch:
        inputs:
            variant:
                description: Variant of core components
                required: false
                type: choice
                default: default
                options:
                    - default
                    - alfasans

concurrency: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.variant }}

jobs:
    snapshot-release:
        name: snapshot release
        if: ${{ github.repository == 'core-ds/core-components' }}
        permissions:
            id-token: write # to use OpenID Connect token for trusted publishing (changesets/action)
        runs-on: ubuntu-latest
        outputs:
            published: ${{ steps.snapshot-release.outputs.published }}
            published-packages: ${{ steps.snapshot-release.outputs.published-packages }}
        env:
            CORE_COMPONENTS_VARIANT: ${{ inputs.variant }}
        steps:
            - uses: actions/checkout@v6

            - name: apply patch
              run: |
                  PATCH_SOURCE='variants/${{ inputs.variant }}.patch'

                  if [ -f "$PATCH_SOURCE" ]; then
                      git apply "$PATCH_SOURCE"
                  fi

            - uses: ./.github/actions/ci-setup
              env:
                  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            - id: snapshot-release
              uses: core-ds/changesets-snapshot-release@v1
              with:
                  version: 'yarn version-packages:snapshot'
                  publish: 'yarn release:snapshot'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
