name: update-screenshots

on: workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    update:
        uses: core-ds/core-components/.github/workflows/update-screenshots.yml@master
        secrets: inherit
        with:
            variant: default
