name: update-screenshots

on:
    workflow_call:
        inputs:
            variant:
                description: Variant of core components
                required: false
                type: string
    workflow_dispatch:
        inputs:
            variant:
                description: Variant of core components
                required: false
                type: choice
                default: alfasans
                options:
                    - alfasans

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.variant }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    build-demo:
        uses: ./.github/workflows/build-demo.yml
        secrets: inherit
        with:
            variant: ${{ inputs.variant }}
            artifact-name: ${{ inputs.variant }}

    update:
        runs-on: ubuntu-latest
        needs: build-demo
        permissions:
            contents: write
        env:
            CORE_COMPONENTS_VARIANT: ${{ inputs.variant }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  lfs: true

            - name: Setup variant
              uses: ./.github/actions/setup-variant
              with:
                  variant: ${{ inputs.variant }}

            - name: Setup CI
              uses: ./.github/actions/ci-setup

            - name: Download build
              uses: actions/download-artifact@v8
              with:
                  name: ${{ inputs.variant }}
                  path: build
                  run-id: ${{ needs.build-demo.outputs.run-id }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Update screenshots
              run: |
                  yarn test:screenshots -u

            - name: Git status
              id: git-status
              uses: actions/github-script@v8
              with:
                  script: |
                      const { stdout } = await exec.getExecOutput('git', ['status', '--porcelain']);

                      return stdout.trim().length > 0;

            - name: Update branch
              if: ${{ fromJson(steps.git-status.outputs.result) }}
              uses: ./.github/actions/commit-and-push
              with:
                  message: 'test: updated screenshots'
