name: upload-pull-request-data

on: workflow_call

jobs:
    upload:
        runs-on: ubuntu-latest
        continue-on-error: true
        env:
            PULL_REQUEST_DATA: ${{ toJson(github.event.pull_request) }}
        steps:
            - name: Write pull request data to json
              run: |
                  mkdir -p pull-request

                  echo $PULL_REQUEST_DATA > pull-request/data.json
                  echo $GITHUB_SHA > pull-request/sha.txt

            - name: Upload pull request data
              uses: actions/upload-artifact@v7
              with:
                  name: pull-request
                  path: pull-request
