name: variants

on:
    workflow_call:
        inputs:
            ref:
                description: Checkout ref
                required: false
                type: string
                default: ${{ github.ref }}
            include-default:
                description: Filter variants
                required: false
                type: boolean
                default: false
        outputs:
            json:
                description: An array of variants of core-components as JSON string
                value: ${{ jobs.variants.outputs.json }}
            empty:
                description: A boolean value to indicate whether an array is empty
                value: ${{ jobs.variants.outputs.empty }}

defaults:
    run:
        shell: bash

jobs:
    variants:
        runs-on: ubuntu-latest
        outputs:
            json: ${{ steps.config.outputs.result }}
            empty: ${{ steps.config.outputs.empty }}
        steps:
            - uses: actions/checkout@v6
              with:
                  ref: ${{ inputs.ref }}

            - id: config
              uses: actions/github-script@v8
              with:
                  script: |
                      const fs = require('node:fs');
                      const file = '${{ github.workspace }}/variants/config.json';
                      let config = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, { encoding: 'utf8' })) : [];

                      config = '${{ inputs.include-default }}' === 'false'
                          ? config.filter(({ variant }) => variant !== 'default')
                          : config;

                      core.setOutput('empty', config.length === 0);

                      return config;
